<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipmentWorkoutSeeder extends Seeder
{
  public function run(): void
  {
    DB::table('equipment_workout')->insert([
      ['id' => 1, 'workout_id' => 1, 'equipment_id' => 8],
      ['id' => 2, 'workout_id' => 2, 'equipment_id' => 11],
      ['id' => 3, 'workout_id' => 3, 'equipment_id' => 4],
      ['id' => 4, 'workout_id' => 4, 'equipment_id' => 4],
      ['id' => 8, 'workout_id' => 6, 'equipment_id' => 12],
      ['id' => 10, 'workout_id' => 7, 'equipment_id' => 13],
      ['id' => 11, 'workout_id' => 8, 'equipment_id' => 7],
      ['id' => 12, 'workout_id' => 9, 'equipment_id' => 7],
      ['id' => 13, 'workout_id' => 10, 'equipment_id' => 4],
      ['id' => 15, 'workout_id' => 11, 'equipment_id' => 5],
      ['id' => 16, 'workout_id' => 12, 'equipment_id' => 8],
      ['id' => 17, 'workout_id' => 13, 'equipment_id' => 1],
      ['id' => 18, 'workout_id' => 14, 'equipment_id' => 8],
      ['id' => 19, 'workout_id' => 15, 'equipment_id' => 8],
      ['id' => 20, 'workout_id' => 16, 'equipment_id' => 4],
      ['id' => 21, 'workout_id' => 16, 'equipment_id' => 5],
      ['id' => 22, 'workout_id' => 17, 'equipment_id' => 4],
      ['id' => 23, 'workout_id' => 17, 'equipment_id' => 5],
      ['id' => 24, 'workout_id' => 18, 'equipment_id' => 1],
      ['id' => 25, 'workout_id' => 18, 'equipment_id' => 15],
      ['id' => 26, 'workout_id' => 19, 'equipment_id' => 1],
      ['id' => 27, 'workout_id' => 19, 'equipment_id' => 15],
      ['id' => 28, 'workout_id' => 20, 'equipment_id' => 8],
      ['id' => 30, 'workout_id' => 21, 'equipment_id' => 16],
      ['id' => 31, 'workout_id' => 22, 'equipment_id' => 8],
      ['id' => 32, 'workout_id' => 23, 'equipment_id' => 8],
      ['id' => 33, 'workout_id' => 24, 'equipment_id' => 8],
      ['id' => 34, 'workout_id' => 25, 'equipment_id' => 8],
      ['id' => 36, 'workout_id' => 26, 'equipment_id' => 17],
      ['id' => 37, 'workout_id' => 27, 'equipment_id' => 3],
      ['id' => 38, 'workout_id' => 28, 'equipment_id' => 4],
      ['id' => 39, 'workout_id' => 29, 'equipment_id' => 1],
      ['id' => 40, 'workout_id' => 30, 'equipment_id' => 18],
      ['id' => 41, 'workout_id' => 31, 'equipment_id' => 20],
      ['id' => 42, 'workout_id' => 32, 'equipment_id' => 3],
      ['id' => 43, 'workout_id' => 32, 'equipment_id' => 5],
      ['id' => 44, 'workout_id' => 33, 'equipment_id' => 3],
      ['id' => 45, 'workout_id' => 34, 'equipment_id' => 3],
      ['id' => 47, 'workout_id' => 35, 'equipment_id' => 21],
      ['id' => 48, 'workout_id' => 36, 'equipment_id' => 18],
      ['id' => 49, 'workout_id' => 37, 'equipment_id' => 3],
      ['id' => 50, 'workout_id' => 38, 'equipment_id' => 4],
      ['id' => 51, 'workout_id' => 39, 'equipment_id' => 3],
      ['id' => 52, 'workout_id' => 39, 'equipment_id' => 5],
      ['id' => 53, 'workout_id' => 40, 'equipment_id' => 17],
      ['id' => 54, 'workout_id' => 41, 'equipment_id' => 3],
      ['id' => 55, 'workout_id' => 42, 'equipment_id' => 4],
      ['id' => 56, 'workout_id' => 42, 'equipment_id' => 5],
      ['id' => 57, 'workout_id' => 43, 'equipment_id' => 3],
      ['id' => 58, 'workout_id' => 44, 'equipment_id' => 8],
      ['id' => 60, 'workout_id' => 46, 'equipment_id' => 8],
      ['id' => 61, 'workout_id' => 45, 'equipment_id' => 22],
      ['id' => 62, 'workout_id' => 47, 'equipment_id' => 3],
      ['id' => 63, 'workout_id' => 47, 'equipment_id' => 5],
      ['id' => 64, 'workout_id' => 48, 'equipment_id' => 3],
      ['id' => 65, 'workout_id' => 48, 'equipment_id' => 5],
      ['id' => 66, 'workout_id' => 49, 'equipment_id' => 4],
      ['id' => 67, 'workout_id' => 49, 'equipment_id' => 9],
      ['id' => 68, 'workout_id' => 50, 'equipment_id' => 3],
      ['id' => 69, 'workout_id' => 50, 'equipment_id' => 5],
      ['id' => 70, 'workout_id' => 51, 'equipment_id' => 8],
      ['id' => 71, 'workout_id' => 52, 'equipment_id' => 8],
      ['id' => 72, 'workout_id' => 53, 'equipment_id' => 12],
      ['id' => 73, 'workout_id' => 54, 'equipment_id' => 3],
      ['id' => 74, 'workout_id' => 54, 'equipment_id' => 5],
      ['id' => 75, 'workout_id' => 55, 'equipment_id' => 4],
      ['id' => 76, 'workout_id' => 56, 'equipment_id' => 3],
      ['id' => 77, 'workout_id' => 57, 'equipment_id' => 24],
      ['id' => 78, 'workout_id' => 58, 'equipment_id' => 4],
      ['id' => 79, 'workout_id' => 59, 'equipment_id' => 3],
      ['id' => 80, 'workout_id' => 60, 'equipment_id' => 8],
      ['id' => 82, 'workout_id' => 61, 'equipment_id' => 25],
      ['id' => 84, 'workout_id' => 62, 'equipment_id' => 26],
      ['id' => 85, 'workout_id' => 63, 'equipment_id' => 26],
      ['id' => 86, 'workout_id' => 64, 'equipment_id' => 4],
      ['id' => 88, 'workout_id' => 66, 'equipment_id' => 27],
      ['id' => 89, 'workout_id' => 65, 'equipment_id' => 27],
      ['id' => 90, 'workout_id' => 67, 'equipment_id' => 9],
      ['id' => 91, 'workout_id' => 68, 'equipment_id' => 3],
      ['id' => 92, 'workout_id' => 69, 'equipment_id' => 3],
      ['id' => 93, 'workout_id' => 69, 'equipment_id' => 5],
      ['id' => 94, 'workout_id' => 70, 'equipment_id' => 4],
      ['id' => 95, 'workout_id' => 71, 'equipment_id' => 1],
      ['id' => 96, 'workout_id' => 71, 'equipment_id' => 2],
      ['id' => 97, 'workout_id' => 72, 'equipment_id' => 6],
      ['id' => 100, 'workout_id' => 73, 'equipment_id' => 28],
      ['id' => 101, 'workout_id' => 74, 'equipment_id' => 29],
      ['id' => 102, 'workout_id' => 75, 'equipment_id' => 4],
      ['id' => 103, 'workout_id' => 75, 'equipment_id' => 5],
      ['id' => 104, 'workout_id' => 76, 'equipment_id' => 3],
      ['id' => 105, 'workout_id' => 76, 'equipment_id' => 5],
      ['id' => 106, 'workout_id' => 77, 'equipment_id' => 4],
      ['id' => 107, 'workout_id' => 77, 'equipment_id' => 5],
      ['id' => 108, 'workout_id' => 78, 'equipment_id' => 17],
      ['id' => 109, 'workout_id' => 79, 'equipment_id' => 8],
      ['id' => 110, 'workout_id' => 80, 'equipment_id' => 32],
      ['id' => 111, 'workout_id' => 81, 'equipment_id' => 32],
      ['id' => 112, 'workout_id' => 82, 'equipment_id' => 4],
      ['id' => 114, 'workout_id' => 83, 'equipment_id' => 33],
      ['id' => 116, 'workout_id' => 84, 'equipment_id' => 16],
      ['id' => 117, 'workout_id' => 85, 'equipment_id' => 4],
      ['id' => 118, 'workout_id' => 86, 'equipment_id' => 3],
      ['id' => 120, 'workout_id' => 87, 'equipment_id' => 34],
      ['id' => 121, 'workout_id' => 28, 'equipment_id' => 34],
      ['id' => 122, 'workout_id' => 87, 'equipment_id' => 4],
      ['id' => 123, 'workout_id' => 88, 'equipment_id' => 3],
      ['id' => 124, 'workout_id' => 88, 'equipment_id' => 5],
      ['id' => 125, 'workout_id' => 89, 'equipment_id' => 35],
      ['id' => 126, 'workout_id' => 90, 'equipment_id' => 3],
      ['id' => 127, 'workout_id' => 90, 'equipment_id' => 5],
      ['id' => 128, 'workout_id' => 91, 'equipment_id' => 8],
      ['id' => 129, 'workout_id' => 92, 'equipment_id' => 1],
      ['id' => 130, 'workout_id' => 93, 'equipment_id' => 5],
      ['id' => 131, 'workout_id' => 93, 'equipment_id' => 9],
      ['id' => 132, 'workout_id' => 94, 'equipment_id' => 5],
      ['id' => 133, 'workout_id' => 94, 'equipment_id' => 9],
      ['id' => 134, 'workout_id' => 95, 'equipment_id' => 1],
      ['id' => 135, 'workout_id' => 96, 'equipment_id' => 3],
      ['id' => 136, 'workout_id' => 97, 'equipment_id' => 2],
      ['id' => 137, 'workout_id' => 98, 'equipment_id' => 33],
      ['id' => 138, 'workout_id' => 99, 'equipment_id' => 33],
      ['id' => 139, 'workout_id' => 100, 'equipment_id' => 8],
      ['id' => 140, 'workout_id' => 101, 'equipment_id' => 8],
      ['id' => 141, 'workout_id' => 102, 'equipment_id' => 3],
      ['id' => 142, 'workout_id' => 103, 'equipment_id' => 17],
      ['id' => 143, 'workout_id' => 104, 'equipment_id' => 8],
    ]);
  }
}
