<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkoutSeeder extends Seeder
{
  public function run(): void
  {
    DB::table('workouts')->insert([
      [
        'id' => 1,
        'title' => 'Cable Seated Row',
        'slug' => 'cable-seated-row',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Cable Seated Row adalah latihan gabungan (compound exercise) untuk melatih otot punggung bagian atas (latissimus dorsi, trapezius, rhomboid), lengan (bisep, trisep), dan inti tubuh, menggunakan mesin kabel horizontal dengan bangku dan pijakan kaki untuk menarik pegangan ke arah perut, bertujuan membangun kekuatan, kepadatan otot, dan memperbaiki postur tubuh dengan gerakan tarik yang stabil.',
        'image' => 'workouts/images/Rm9tZFNQguADKMpAo1f7BFq1XrfUFyjUR9rwTm3L.png',
        'gif' => 'workouts/gifs/8x4i2qpndU293YZmdOlXISvPHwEKds5kLyomQ1CC.gif',
        'image_thumb' => 'workouts/images/thumbs/Rm9tZFNQguADKMpAo1f7BFq1XrfUFyjUR9rwTm3L.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.75,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-14 09:53:14',
        'updated_at' => '2026-01-14 09:53:14',
      ],
      [
        'id' => 2,
        'title' => 'Lateral Raise Machine',
        'slug' => 'lateral-raise-machine',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Lateral raise machine adalah alat gym untuk melatih otot bahu (deltoid lateral) dengan gerakan mengangkat beban ke samping, menggunakan bantalan dada dan lengan yang empuk serta tumpukan beban untuk gerakan terpandu yang stabil, ideal untuk pemula karena membatasi gerakan liar dan mengisolasi bahu, menciptakan bentuk bahu lebar dan V-shape tubuh. Alat ini menawarkan jalur gerakan tetap dan konsisten, memungkinkan fokus penuh pada kontraksi otot bahu saat mendorong lengan ke samping hingga sejajar lantai, lalu kembali perlahan.',
        'image' => 'workouts/images/RDH1MOdJ2prHQqQxVREz6DyrCvosQeMD3E7ZIi3y.png',
        'gif' => 'workouts/gifs/s5nFDQROov2diepu5qXwKOEcoHun9d0QsmfeGqUZ.gif',
        'image_thumb' => 'workouts/images/thumbs/RDH1MOdJ2prHQqQxVREz6DyrCvosQeMD3E7ZIi3y.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.35,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-14 10:04:06',
        'updated_at' => '2026-01-14 10:04:06',
      ],
      [
        'id' => 3,
        'title' => 'Barbell Deadlift',
        'slug' => 'barbell-deadlift',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Barbell deadlift adalah latihan kekuatan fundamental di mana Anda mengangkat barbel dari lantai hingga berdiri tegak dengan punggung lurus, melibatkan hampir seluruh otot tubuh, terutama punggung, kaki, dan pinggul, untuk membangun kekuatan keseluruhan dan massa otot, serta meningkatkan performa atletik lainnya. Gerakan ini termasuk dalam "Big Three" powerlifting (bersama squat dan bench press) dan sangat efektif namun membutuhkan teknik yang benar untuk mencegah cedera.',
        'image' => 'workouts/images/3AmgP1SLJDfypCRpSDinDTY6GrzC7Vvkm1KAnVbQ.png',
        'gif' => 'workouts/gifs/uQwvZVBNKIXSOUuornqNXsiXp1w0cDZ9kcFPLrDz.gif',
        'image_thumb' => 'workouts/images/thumbs/3AmgP1SLJDfypCRpSDinDTY6GrzC7Vvkm1KAnVbQ.png',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 1.20,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-14 10:32:40',
        'updated_at' => '2026-01-14 10:32:40',
      ],
      [
        'id' => 4,
        'title' => 'Barbell Bent Over Row',
        'slug' => 'barbell-bent-over-row',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Barbell Bent Over Row adalah latihan angkat beban gabungan yang fokus melatih otot punggung (latissimus dorsi, trapezius, rhomboid) dan lengan (bisep), sambil melibatkan inti dan hamstring untuk stabilitas, dengan cara menarik barbel ke arah perut sambil membungkuk ke depan dengan punggung lurus. Gerakan ini membangun kekuatan punggung, memperbaiki postur, dan meningkatkan hipertrofi otot secara keseluruhan.',
        'image' => 'workouts/images/Z6wHsEOMj9SJs231qDdSlmqqSzohzKce6W0nuQyD.png',
        'gif' => 'workouts/gifs/dgEV8tijEPn3RIWgGQDo0TRpGUIK9EyipxbCk6hh.gif',
        'image_thumb' => 'workouts/images/thumbs/Z6wHsEOMj9SJs231qDdSlmqqSzohzKce6W0nuQyD.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-14 10:42:58',
        'updated_at' => '2026-01-15 09:25:21',
      ],
      [
        'id' => 6,
        'title' => 'Assisted Dip',
        'slug' => 'assisted-dip',
        'type' => 'assisted',
        'workout_category_id' => 1,
        'description' => '"Assisted dips" (dips dibantu) adalah latihan beban tubuh bagian atas di mana sebagian berat badan Anda ditopang, sehingga memungkinkan Anda melakukan gerakan dips secara terkontrol bahkan jika Anda belum memiliki kekuatan yang cukup untuk melakukan dips penuh tanpa bantuan.',
        'image' => 'workouts/images/8q8ESQLBz9iKLLwmQIXaSpiRUqYmcQgXzd9Auls0.png',
        'gif' => 'workouts/gifs/gNUFod6IiC0Ry7Rop4atnPEnsYvw0rHvBDKmNIfu.gif',
        'image_thumb' => 'workouts/images/thumbs/8q8ESQLBz9iKLLwmQIXaSpiRUqYmcQgXzd9Auls0.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-15 09:37:52',
        'updated_at' => '2026-01-15 10:09:23',
      ],
      [
        'id' => 7,
        'title' => 'Ball Sit Up',
        'slug' => 'ball-sit-up',
        'type' => 'bodyweight',
        'workout_category_id' => 5,
        'description' => 'Ball sit-up (sit-up menggunakan bola stabilitas atau Swiss ball) adalah latihan efektif yang menargetkan beberapa otot inti tubuh. Penggunaan bola yang tidak stabil memaksa otot-otot Anda bekerja lebih keras untuk menjaga keseimbangan, sehingga melibatkan lebih banyak serat otot dibandingkan sit-up tradisional di lantai.',
        'image' => 'workouts/images/mAuitxYZGFY0uY2jiL6GbWvax2sh7jLmUsUmkSTm.png',
        'gif' => 'workouts/gifs/QcyoAUBSEtk5Kr2q5ZEPLCLyYvlOmFZBlAiCg7UM.gif',
        'image_thumb' => 'workouts/images/thumbs/mAuitxYZGFY0uY2jiL6GbWvax2sh7jLmUsUmkSTm.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-15 10:19:38',
        'updated_at' => '2026-01-15 10:20:13',
      ],
      [
        'id' => 8,
        'title' => 'Band Chest Fly',
        'slug' => 'band-chest-fly',
        'type' => 'resistance-band',
        'workout_category_id' => 1,
        'description' => '"Band chest fly" adalah latihan beban yang menggunakan resistance band untuk melatih otot dada (pectoralis mayor).',
        'image' => 'workouts/images/O83MBXQrdkBOHl9IyRwbJEvsUDtF2Z9FdLsMGr7G.png',
        'gif' => 'workouts/gifs/vqrvsD8SkVG1QGDx20SImBX9QpFNMIsH0i4GRwqG.gif',
        'image_thumb' => 'workouts/images/thumbs/O83MBXQrdkBOHl9IyRwbJEvsUDtF2Z9FdLsMGr7G.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 00:08:03',
        'updated_at' => '2026-01-16 00:08:03',
      ],
      [
        'id' => 9,
        'title' => 'Band Chest Press',
        'slug' => 'band-chest-press',
        'type' => 'resistance-band',
        'workout_category_id' => 1,
        'description' => 'Band chest press adalah variasi latihan dorong untuk otot dada (pektoralis), bahu depan (deltoid anterior), dan trisep, menggunakan resistance band sebagai beban untuk meniru gerakan bench press dengan cara mendorong band menjauh dari dada hingga lengan hampir lurus, lalu kembali perlahan, efektif untuk membangun kekuatan tubuh bagian atas di rumah atau gym.',
        'image' => 'workouts/images/VzWISaQIBfkVVJmiy5pFYlRdvGH0g61WskjYsJTN.png',
        'gif' => 'workouts/gifs/cD3g4I8xCb0BZRHCYG0iC9lFZcoQz1lAzub4Ltov.gif',
        'image_thumb' => 'workouts/images/thumbs/VzWISaQIBfkVVJmiy5pFYlRdvGH0g61WskjYsJTN.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 00:12:45',
        'updated_at' => '2026-01-16 00:12:45',
      ],
      [
        'id' => 10,
        'title' => 'Barbell Floor Press',
        'slug' => 'barbell-floor-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Barbell Floor Press adalah variasi bench press yang dilakukan di lantai, bukan di bangku, dengan dumbbell atau barbell, membatasi rentang gerak (ROM) sehingga lebih menekankan pada kekuatan penguncian (lockout) trisep dan bahu, mengurangi tekanan pada bahu, serta menargetkan otot dada, trisep, dan bahu depan, ideal untuk membangun kekuatan tubuh bagian atas dengan risiko cedera bahu lebih rendah karena tidak ada leg drive.',
        'image' => 'workouts/images/QulNlCx74fVOTQh6ByVEr730cGZL5jIOW12iCyY0.png',
        'gif' => 'workouts/gifs/c663B4t27RUsFZ3jaIeFys2QsTtvWHbnb0DQUY25.gif',
        'image_thumb' => 'workouts/images/thumbs/QulNlCx74fVOTQh6ByVEr730cGZL5jIOW12iCyY0.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 1.10,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 00:16:46',
        'updated_at' => '2026-01-16 00:16:46',
      ],
      [
        'id' => 11,
        'title' => 'Bench Dip Knee Bent',
        'slug' => 'bench-dip-knee-bent',
        'type' => 'bodyweight',
        'workout_category_id' => 1,
        'description' => 'Bench dip knee bent adalah variasi latihan bench dip yang dimodifikasi untuk mengurangi intensitasnya. Fokus utama latihan ini adalah melatih otot trisep (bagian belakang lengan atas) dan otot dada, dengan intensitas yang lebih ringan dibandingkan variasi standar karena tumpuan sebagian berat badan berada pada lutut, bukan hanya pada tangan.',
        'image' => 'workouts/images/fBdvEaKPehs23HaPa44cPeBJG8Lp0ypv4zQNhf2u.png',
        'gif' => 'workouts/gifs/O7nkbcnQSIhJq8s8FTl7VoP6Fp36HIaI1Odp2gBR.gif',
        'image_thumb' => 'workouts/images/thumbs/fBdvEaKPehs23HaPa44cPeBJG8Lp0ypv4zQNhf2u.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 00:24:14',
        'updated_at' => '2026-01-16 00:25:13',
      ],
      [
        'id' => 12,
        'title' => 'Cable Crossover',
        'slug' => 'cable-crossover',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Deskripsi Cable Crossover bisa merujuk pada dua hal: latihan kebugaran yang melatih otot dada menggunakan mesin kabel, atau kabel jaringan komputer yang menghubungkan dua perangkat sejenis; dalam konteks kebugaran, ini adalah latihan isolasi dada yang efektif, sementara dalam jaringan, ini adalah kabel Ethernet yang berfungsi menghubungkan perangkat tanpa router, dengan prinsip dasar yang sama-sama \'menyilangkan\' (crossover) jalur.',
        'image' => 'workouts/images/wtKw0g23wGbAu1BjlvkGu1lXTtxiLA641Wv4x3RX.png',
        'gif' => 'workouts/gifs/eauxRxfW9YxuZLEEEruxpnHfGZx5JTDpR6zyb8GY.gif',
        'image_thumb' => 'workouts/images/thumbs/wtKw0g23wGbAu1BjlvkGu1lXTtxiLA641Wv4x3RX.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 00:35:16',
        'updated_at' => '2026-01-16 00:35:16',
      ],
      [
        'id' => 13,
        'title' => 'Butterfly Sit Up',
        'slug' => 'butterfly-sit-up',
        'type' => 'bodyweight',
        'workout_category_id' => 5,
        'description' => 'Butterfly sit-up adalah variasi sit-up yang melatih otot perut (terutama rektus abdominis dan transversus abdominis) serta otot punggung bawah, dengan posisi kaki membentuk berlian (telapak kaki saling menempel, lutut terbuka ke samping) yang memungkinkan gerakan lebih luas dan meningkatkan kontraksi perut. Latihan ini membangun kekuatan inti, fleksibilitas pinggul, dan stabilitas tulang belakang, berbeda dari sit-up biasa karena mengurangi keterlibatan fleksor pinggul dan memungkinkan tubuh bagian atas mendekat ke panggul untuk kontraksi lebih kuat.',
        'image' => 'workouts/images/3UGgHZzDd1lIbjLGpIzxNMG3LCaPT85NPqzZaE8e.png',
        'gif' => 'workouts/gifs/5RXrLSvLmTSN2cIu6MzA8pEtU0iEMm91fMOHAGTt.gif',
        'image_thumb' => 'workouts/images/thumbs/3UGgHZzDd1lIbjLGpIzxNMG3LCaPT85NPqzZaE8e.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 00:39:20',
        'updated_at' => '2026-01-16 00:43:14',
      ],
      [
        'id' => 14,
        'title' => 'Cable Chest Fly',
        'slug' => 'cable-chest-fly',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Cable fly adalah latihan isolasi otot dada menggunakan mesin kabel yang memberikan ketegangan konstan di seluruh gerakan, berbeda dari dumbbell fly yang lebih berat di awal. Gerakan ini melibatkan menggerakkan pegangan kabel dari posisi terbuka (sisi tubuh) ke depan dada, melatih otot dada (pektoralis mayor), serta otot penstabil bahu (deltoid) dan trisep. Keunggulannya terletak pada isolasi otot dada yang lebih baik, lebih aman untuk sendi bahu, dan dapat divariasikan (ketinggian kabel) untuk menargetkan area dada berbeda (atas, tengah, bawah).',
        'image' => 'workouts/images/rhXCbTqZqpVydrJSgTwoOsIuebSIfmCALgh3b6sR.png',
        'gif' => 'workouts/gifs/OfWZo9SWIgTYttwdFYZSgYbuczVfUkZhs0SNlpF1.gif',
        'image_thumb' => 'workouts/images/thumbs/rhXCbTqZqpVydrJSgTwoOsIuebSIfmCALgh3b6sR.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 00:45:59',
        'updated_at' => '2026-01-16 00:45:59',
      ],
      [
        'id' => 15,
        'title' => 'Cable Shrug',
        'slug' => 'cable-shrug',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Cable shrug adalah latihan isolasi untuk otot trapezius (otot bahu dan leher bagian atas) menggunakan mesin katrol kabel, yang memberikan ketegangan konstan sepanjang gerakan, berbeda dari beban bebas, sehingga efektif membangun kekuatan dan ukuran otot trapezius dengan gerakan mengangkat bahu ke arah telinga sambil menjaga lengan tetap lurus dan menurunkan beban secara terkontrol.',
        'image' => 'workouts/images/Z76ytuIpIU02SXNXtFaHNrFoc29zZ6atCzwMwDCW.png',
        'gif' => 'workouts/gifs/NrRvZ9qmDPOiFrrDqgueV1fqmIzLuUUpWqn5Axqb.gif',
        'image_thumb' => 'workouts/images/thumbs/Z76ytuIpIU02SXNXtFaHNrFoc29zZ6atCzwMwDCW.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 00:48:23',
        'updated_at' => '2026-01-16 00:48:23',
      ],
      [
        'id' => 16,
        'title' => 'Barbell Bench Press',
        'slug' => 'barbell-bench-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Barbell bench press adalah latihan kekuatan fundamental untuk tubuh bagian atas, dilakukan dengan berbaring telentang di bangku datar sambil mengangkat barbel dari dada ke atas hingga lengan lurus, melatih otot dada utama (pectoralis), trisep, dan bahu (deltoid), serta membangun kekuatan dan massa otot tubuh bagian atas secara signifikan. Gerakan ini penting dalam dunia kebugaran karena merupakan ujian kekuatan dorong tubuh bagian atas dan sering disebut sebagai salah satu dari "tiga besar" dalam powerlifting, menuntut teknik yang benar untuk keamanan dan efektivitas maksimal.',
        'image' => 'workouts/images/HXhNf0oxkruRiL8tcUFFXuyradswjnDpVU2SqEMn.png',
        'gif' => 'workouts/gifs/Xikx3kqHYVciNLZ0o9ZEK0T5NjBdW1kYGFrIdXan.gif',
        'image_thumb' => 'workouts/images/thumbs/HXhNf0oxkruRiL8tcUFFXuyradswjnDpVU2SqEMn.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 1.20,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 01:48:19',
        'updated_at' => '2026-01-16 01:48:19',
      ],
      [
        'id' => 17,
        'title' => 'Barbell Incline Bench Press',
        'slug' => 'barbell-incline-bench-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Incline Barbell Bench Press adalah variasi latihan bench press di bangku miring (biasanya 30-45 derajat) yang lebih fokus melatih dada bagian atas (upper chest), bahu depan, dan trisep, ideal untuk membangun massa otot di area dada yang sering tertinggal, dilakukan dengan menggerakkan barbel dari dada bagian atas ke posisi awal dengan siku membentuk sudut sekitar 45 derajat, menjaga stabilitas core, dan mengontrol tempo gerakan untuk hasil optimal.',
        'image' => 'workouts/images/4AemPIGQFHy8DrG7a2KEg1L7EgIbeMFnLj2mjM9O.png',
        'gif' => 'workouts/gifs/fMkxTEKrUejWlP3xDYM3ALVcGoJZIHGPcHNNCkhj.gif',
        'image_thumb' => 'workouts/images/thumbs/4AemPIGQFHy8DrG7a2KEg1L7EgIbeMFnLj2mjM9O.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 0.90,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 01:53:48',
        'updated_at' => '2026-01-23 01:53:10',
      ],
      [
        'id' => 18,
        'title' => 'Tricep Dips',
        'slug' => 'tricep-dips',
        'type' => 'bodyweight',
        'workout_category_id' => 1,
        'description' => 'Triceps dips adalah latihan beban tubuh (bodyweight) yang efektif untuk memperkuat otot trisep di belakang lengan, dada, dan bahu, dilakukan dengan menopang tubuh di bangku atau palang paralel lalu menurunkan dan mengangkat tubuh menggunakan kekuatan lengan, menjadikannya latihan serbaguna untuk membangun kekuatan dan massa otot tubuh bagian atas, yang bisa dimodifikasi dari mudah hingga sulit.',
        'image' => 'workouts/images/FmubtOJf6pgR2285Mb0f3Wfv0lo7OIyhefsGMPkc.png',
        'gif' => 'workouts/gifs/CXW9Vws53hcpSwhPniqMt8y940DkL1ZblANjqHFh.gif',
        'image_thumb' => 'workouts/images/thumbs/FmubtOJf6pgR2285Mb0f3Wfv0lo7OIyhefsGMPkc.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 02:00:28',
        'updated_at' => '2026-01-29 08:46:32',
      ],
      [
        'id' => 19,
        'title' => 'Chest Dips',
        'slug' => 'chest-dips',
        'type' => 'bodyweight',
        'workout_category_id' => 1,
        'description' => 'Chest dips adalah latihan beban tubuh tingkat lanjut menggunakan palang sejajar untuk melatih otot dada (pektoralis mayor dan minor), bahu (deltoid depan), dan trisep, dengan cara menurunkan dan mengangkat tubuh sambil sedikit mencondongkan badan ke depan untuk menargetkan dada secara maksimal, sangat efektif membangun kekuatan dorong tubuh bagian atas, dan dapat dimodifikasi dengan bantuan atau beban tambahan.',
        'image' => 'workouts/images/mEfRttO3ZqtIKrwrgfws3VupvIW2t2MYWqSHfKT8.png',
        'gif' => 'workouts/gifs/qXijojaVEvwXfpzx30tjV4FxkxaxmVsEFoT1ACEy.gif',
        'image_thumb' => 'workouts/images/thumbs/mEfRttO3ZqtIKrwrgfws3VupvIW2t2MYWqSHfKT8.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 02:04:32',
        'updated_at' => '2026-01-16 02:04:32',
      ],
      [
        'id' => 20,
        'title' => 'Cable Straight Bar Tricep Pushdown',
        'slug' => 'cable-straight-bar-tricep-pushdown',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Triceps pushdown bar lurus kabel (cable straight bar triceps pushdown) adalah latihan beban populer yang menargetkan otot trisep brachii di bagian belakang lengan atas. Latihan ini melibatkan penggunaan mesin katrol kabel dan attachment bar lurus.',
        'image' => 'workouts/images/SHS92NoCYcQU1tgsm3KJkmR5nISOUk9orfPuj2w6.png',
        'gif' => 'workouts/gifs/PMvBsfoslqxqHkoYHITUU1TIBESlzQpodXhoUHpG.gif',
        'image_thumb' => 'workouts/images/thumbs/SHS92NoCYcQU1tgsm3KJkmR5nISOUk9orfPuj2w6.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 02:23:11',
        'updated_at' => '2026-01-16 02:23:56',
      ],
      [
        'id' => 21,
        'title' => 'Pec Deck Fly / Machine Chest Fly',
        'slug' => 'pec-deck-fly',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Machine chest fly (atau Pec Deck Fly) adalah alat latihan isolasi otot dada yang memandu gerakan mendorong lengan ke depan secara melengkung, meniru gerakan memeluk, dengan tujuan membangun otot dada (pektoralis mayor/minor) dan bahu dengan lebih stabil dan aman, cocok untuk pemula karena jalur gerakan tetap dan minim cedera.',
        'image' => 'workouts/images/UhcB0ZratDrrC6yms2Tvz6hNBVGCZydP00ZjnfXg.png',
        'gif' => 'workouts/gifs/Fg4uPbVjQ1m6tDqno6DUXyJvp7iYiCDHsk7hbQnj.gif',
        'image_thumb' => 'workouts/images/thumbs/UhcB0ZratDrrC6yms2Tvz6hNBVGCZydP00ZjnfXg.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 02:33:17',
        'updated_at' => '2026-01-19 09:02:05',
      ],
      [
        'id' => 22,
        'title' => 'Wide Grip Lat Pulldown',
        'slug' => 'wide-grip-lat-pulldown',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Lat pulldown adalah latihan beban untuk memperkuat otot punggung, terutama otot latissimus dorsi (sayap punggung), dengan cara menarik palang berbeban ke bawah menuju dada menggunakan mesin kabel, meniru gerakan pull-up namun lebih terkontrol dan bisa disesuaikan beban serta genggamannya, efektif untuk membentuk punggung lebar dan V-shape, serta melatih bisep dan punggung tengah.',
        'image' => 'workouts/images/FPKJfADFA5v7HFqkV52HympLwVjcoY0bO1Z9wEDZ.png',
        'gif' => 'workouts/gifs/6VTfDbXBLS4os0O10W1QQhPvLTkbfbPuOLbtKJD5.gif',
        'image_thumb' => 'workouts/images/thumbs/FPKJfADFA5v7HFqkV52HympLwVjcoY0bO1Z9wEDZ.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 06:05:21',
        'updated_at' => '2026-01-16 08:16:44',
      ],
      [
        'id' => 23,
        'title' => 'Neutral / V Grip Lat Pulldown',
        'slug' => 'neutral-lat-pulldown',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Neutral grip lat pulldown (tarikan ke bawah lat dengan pegangan netral) adalah latihan punggung atas dan tengah yang efektif, menargetkan otot latissimus dorsi, rhomboid, dan trapezius, serta bisep sebagai otot pendukung.',
        'image' => 'workouts/images/eNNYDtc3wMtCa5Q6EbYGhlRXyfn7PhE2D3ZQHul6.png',
        'gif' => 'workouts/gifs/XATCVWa8xLuwqoffjj2gzLruXQkdaFTQarmTqxjC.gif',
        'image_thumb' => 'workouts/images/thumbs/eNNYDtc3wMtCa5Q6EbYGhlRXyfn7PhE2D3ZQHul6.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 06:35:57',
        'updated_at' => '2026-01-16 06:35:57',
      ],
      [
        'id' => 24,
        'title' => 'Standing Straight-Arm Pulldown',
        'slug' => 'standing-straight-arm-pulldown',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Standing Straight-Arm Pulldown adalah latihan isolasi punggung menggunakan mesin kabel atau resistance band, yang mengisolasi otot latissimus dorsi (lats) dengan menjaga siku tetap lurus saat menarik beban ke bawah menuju pinggul, fokus pada peregangan dan kontraksi otot punggung tanpa bantuan bisep, sangat efektif untuk membangun kekuatan dan definisi otot punggung atas.',
        'image' => 'workouts/images/PTE5oyMOcNMiOZcOoDNpCCxoQp5e6iPAB0CDiqat.png',
        'gif' => 'workouts/gifs/1TofVnQrBp0DoUYMMiefDHNpng90wOpGxXgJXoCz.gif',
        'image_thumb' => 'workouts/images/thumbs/PTE5oyMOcNMiOZcOoDNpCCxoQp5e6iPAB0CDiqat.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 06:47:35',
        'updated_at' => '2026-01-16 06:47:35',
      ],
      [
        'id' => 25,
        'title' => 'Supinated / Reverse Grip Lat Pulldown',
        'slug' => 'supinated-grip-lat-pulldown',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Supinated Lat Pulldown adalah variasi latihan lat pulldown dengan pegangan underhand.',
        'image' => 'workouts/images/kghfOhXELQrpnTZziPPqBaPNGStxgFTaoGEMn6hG.png',
        'gif' => 'workouts/gifs/Z5IpigrXaTgDHeb0uHGyd5KL150XeZiVO6N5yOX6.gif',
        'image_thumb' => 'workouts/images/thumbs/kghfOhXELQrpnTZziPPqBaPNGStxgFTaoGEMn6hG.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 07:11:06',
        'updated_at' => '2026-01-16 07:11:30',
      ],
      [
        'id' => 26,
        'title' => 'Ez-Bar Curl',
        'slug' => 'ez-bar-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'EZ bar curl adalah latihan angkat beban untuk bisep menggunakan EZ bar (batang melengkung/zig-zag) yang dirancang ergonomis untuk mengurangi ketegangan pada pergelangan tangan dan siku, sehingga memungkinkan otot bisep bekerja lebih efektif dan nyaman dibandingkan bar lurus.',
        'image' => 'workouts/images/K2tjSbcozCRNc8nt8iO9FJUdmUj4eKD7SiHvFIie.png',
        'gif' => 'workouts/gifs/QUsLW5H8IGokcKaMdtqtDgWYKPpWRt5aUTh0zJgT.gif',
        'image_thumb' => 'workouts/images/thumbs/K2tjSbcozCRNc8nt8iO9FJUdmUj4eKD7SiHvFIie.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 08:20:32',
        'updated_at' => '2026-01-17 09:01:14',
      ],
      [
        'id' => 27,
        'title' => 'Dumbbell Bicep Curl',
        'slug' => 'dumbbell-bicep-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Dumbbell Biceps Curl adalah latihan isolasi untuk memperkuat otot bisep dengan mengangkat dumbbell dari posisi lengan lurus hingga ke bahu secara terkontrol.',
        'image' => 'workouts/images/FWKK0jlOdgsnQIldqqAUDrs1pYJCCNlHUVYXdZiR.png',
        'gif' => 'workouts/gifs/4PLKBsB9AWhrMog6VulEUYBcoGmVjoxQeuHMkBYP.gif',
        'image_thumb' => 'workouts/images/thumbs/FWKK0jlOdgsnQIldqqAUDrs1pYJCCNlHUVYXdZiR.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 08:25:44',
        'updated_at' => '2026-01-22 21:48:41',
      ],
      [
        'id' => 28,
        'title' => 'Squat / Back Squat',
        'slug' => 'back-squat',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Back squat adalah latihan beban dasar yang melatih paha, bokong, dan inti dengan menopang barbel di punggung atas lalu jongkok dan berdiri kembali.',
        'image' => 'workouts/images/lRZtG9dyJyuGpfSnNTklHvUZmfDL3XoNa5o8eh9O.png',
        'gif' => 'workouts/gifs/eRqt7JLnWalpcVqmLxBDEWLiGb7zCqoUkq1KJn9N.gif',
        'image_thumb' => 'workouts/images/thumbs/lRZtG9dyJyuGpfSnNTklHvUZmfDL3XoNa5o8eh9O.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 1.20,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 08:31:23',
        'updated_at' => '2026-01-22 22:05:18',
      ],
      [
        'id' => 29,
        'title' => 'Leg Extension',
        'slug' => 'leg-extension',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Leg extension adalah latihan isolasi untuk melatih otot paha depan (quadriceps) menggunakan mesin dengan gerakan meluruskan lutut secara terkontrol.',
        'image' => 'workouts/images/0g8XZ8DeOFFaYzkwIV4EFUhXdaYfmoZ9owdiQGLQ.png',
        'gif' => 'workouts/gifs/tpJ2M9ODaZxusA9iK98OUBUMswDMzTP8dYqOL5bQ.gif',
        'image_thumb' => 'workouts/images/thumbs/0g8XZ8DeOFFaYzkwIV4EFUhXdaYfmoZ9owdiQGLQ.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 08:46:46',
        'updated_at' => '2026-01-16 08:46:46',
      ],
      [
        'id' => 30,
        'title' => 'Leg Press',
        'slug' => 'leg-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Leg press adalah latihan kekuatan menggunakan mesin untuk melatih paha, hamstring, dan glutes dengan stabilitas tinggi.',
        'image' => 'workouts/images/kHuuozHUqzEN0Gdtx74DciBdbregU9vqk30gRFta.png',
        'gif' => 'workouts/gifs/kEFzCdLs38pUmmyXWCS3ZhlsiOEk1CItz87Llrgl.gif',
        'image_thumb' => 'workouts/images/thumbs/kHuuozHUqzEN0Gdtx74DciBdbregU9vqk30gRFta.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.20,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 08:49:11',
        'updated_at' => '2026-01-22 22:10:23',
      ],
      [
        'id' => 31,
        'title' => 'Hammer Strength High Row',
        'slug' => 'hammer-strength-high-row',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'High Row adalah latihan punggung untuk membangun ketebalan dan kekuatan lat serta punggung atas.',
        'image' => 'workouts/images/0oFBkL74So0CUReNj9f6mNP7KbKzGAeJPGQhz0nO.png',
        'gif' => 'workouts/gifs/5sC78nwoO5USAhUWCR8YE5It4cYNeuOSM2LhUsZA.gif',
        'image_thumb' => 'workouts/images/thumbs/0oFBkL74So0CUReNj9f6mNP7KbKzGAeJPGQhz0nO.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 20:18:45',
        'updated_at' => '2026-01-22 09:03:14',
      ],
      [
        'id' => 32,
        'title' => 'Dumbbell Shoulder Press',
        'slug' => 'dumbbell-shoulder-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Dumbbell shoulder press melatih otot bahu, trisep, dan dada atas dengan gerakan menekan ke atas kepala.',
        'image' => 'workouts/images/EghUJh5JNFxiV5EssGUfac9fEALwx4E8UAACJ3NC.png',
        'gif' => 'workouts/gifs/yAWPMgHQxLvDE2GElARGSHDP0DvaK8J0Ej0HYJUa.gif',
        'image_thumb' => 'workouts/images/thumbs/EghUJh5JNFxiV5EssGUfac9fEALwx4E8UAACJ3NC.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 20:25:47',
        'updated_at' => '2026-01-16 20:25:47',
      ],
      [
        'id' => 33,
        'title' => 'Dumbbell Lateral Raise',
        'slug' => 'dumbbell-lateral-raise',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Dumbbell lateral raise adalah latihan isolasi untuk membangun lebar bahu.',
        'image' => 'workouts/images/PP6QAond7XtItoMrumj65ovSSzuYvYMRLSjHykRZ.png',
        'gif' => 'workouts/gifs/CchbpUZ6rmEdmfShJaSBUmko0TRVKL92225hVPAC.gif',
        'image_thumb' => 'workouts/images/thumbs/PP6QAond7XtItoMrumj65ovSSzuYvYMRLSjHykRZ.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 20:37:43',
        'updated_at' => '2026-01-16 20:37:43',
      ],
      [
        'id' => 34,
        'title' => 'Dumbbell Rear Delt Row',
        'slug' => 'dumbbell-rear-delt-row',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Rear delt row melatih bahu belakang dan punggung atas untuk postur dan stabilitas bahu.',
        'image' => 'workouts/images/euTeyXKhxmBTTcPfxo73ipqAFwzvEaw1YoeNqvFc.png',
        'gif' => 'workouts/gifs/N0mMWS1jfD0SLKAymoJk1n7f17Z0wNrPfU7tqCxB.gif',
        'image_thumb' => 'workouts/images/thumbs/euTeyXKhxmBTTcPfxo73ipqAFwzvEaw1YoeNqvFc.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-16 21:02:35',
        'updated_at' => '2026-01-16 21:02:35',
      ],
      [
        'id' => 35,
        'title' => 'Shoulder Press Machine',
        'slug' => 'shoulder-press-machine',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Machine shoulder press memberikan stabilitas tinggi untuk melatih otot bahu.',
        'image' => 'workouts/images/BzxYIjNK3lkBxBHT6FZRCTgA0RxHGU2p7dRMgYX3.png',
        'gif' => 'workouts/gifs/CTYvv5C3xXy76qQydcVYUIww4naXapCkoeKqz6EX.gif',
        'image_thumb' => 'workouts/images/thumbs/BzxYIjNK3lkBxBHT6FZRCTgA0RxHGU2p7dRMgYX3.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 07:54:03',
        'updated_at' => '2026-01-17 08:00:38',
      ],
      [
        'id' => 36,
        'title' => 'V Leg Press',
        'slug' => 'v-leg-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'V Leg Press (Vertical Leg Press) adalah varian leg press dengan posisi kaki menghadap ke atas untuk melatih paha, hamstring, dan glutes secara efektif.',
        'image' => 'workouts/images/0FdZUh3XwZxfCePSAGEUmKZUyUtyAU65lkWGw782.png',
        'gif' => 'workouts/gifs/Jfsi4LdQvZSZr8V5fK1nsSbNukjudba2wbh5hmYv.gif',
        'image_thumb' => 'workouts/images/thumbs/0FdZUh3XwZxfCePSAGEUmKZUyUtyAU65lkWGw782.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.20,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 08:05:30',
        'updated_at' => '2026-01-17 08:05:30',
      ],
      [
        'id' => 37,
        'title' => 'Dumbbell Front Raise',
        'slug' => 'dumbbell-front-raise',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Dumbbell front raise adalah latihan isolasi untuk melatih otot bahu depan dengan gerakan mengangkat beban ke depan secara terkontrol.',
        'image' => 'workouts/images/BT3mjU6c4NERLhlVfKOuGOog1H2XdvQTnm8C8gTi.png',
        'gif' => 'workouts/gifs/daxG0cYti87gcBARMouXusxcvdWmo5agdyQDBeMY.gif',
        'image_thumb' => 'workouts/images/thumbs/BT3mjU6c4NERLhlVfKOuGOog1H2XdvQTnm8C8gTi.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 08:15:05',
        'updated_at' => '2026-01-17 08:15:05',
      ],
      [
        'id' => 38,
        'title' => 'Barbell Shrug',
        'slug' => 'barbell-shrug',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Barbell shrug adalah latihan isolasi untuk memperkuat otot trapezius dengan mengangkat bahu secara vertikal.',
        'image' => 'workouts/images/lrtjIYPAZKXjY0gUZLW0crqNVqiPKmuQ2UoSaYAC.png',
        'gif' => 'workouts/gifs/WxGm0JZjdqfd95KHjvUC1BZ6cCdA9Cdr4UVzWbpz.gif',
        'image_thumb' => 'workouts/images/thumbs/lrtjIYPAZKXjY0gUZLW0crqNVqiPKmuQ2UoSaYAC.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 1.20,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 08:33:20',
        'updated_at' => '2026-01-17 08:33:20',
      ],
      [
        'id' => 39,
        'title' => 'Dumbbell Reverse Wrist Curl',
        'slug' => 'dumbbell-reverse-wrist-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Reverse wrist curl melatih otot ekstensor lengan bawah untuk meningkatkan kekuatan pergelangan dan grip.',
        'image' => 'workouts/images/zW54oAvpK6knrbfPvX2JQvqlgNXdW7SRtfuNpJ7f.png',
        'gif' => 'workouts/gifs/mpxk8fG2c3XZVHc7SnmQoSiEQSFI9AEQivzOmyS0.gif',
        'image_thumb' => 'workouts/images/thumbs/zW54oAvpK6knrbfPvX2JQvqlgNXdW7SRtfuNpJ7f.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 08:43:10',
        'updated_at' => '2026-01-17 08:43:10',
      ],
      [
        'id' => 40,
        'title' => 'Ez-Bar Close Grip Curl',
        'slug' => 'ez-bar-close-grip-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'EZ Bar Close Grip Curl menargetkan bagian luar bisep dengan genggaman rapat dan stres sendi yang lebih rendah.',
        'image' => 'workouts/images/O3PYZMqYKQ0vmvVYPLZLLY3Q9ErgvrRBJ7Y6LAkV.png',
        'gif' => 'workouts/gifs/helKwRId72Xe8XNBvhItVzhIK8DdMBM8HZH14fM9.gif',
        'image_thumb' => 'workouts/images/thumbs/O3PYZMqYKQ0vmvVYPLZLLY3Q9ErgvrRBJ7Y6LAkV.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 09:00:49',
        'updated_at' => '2026-01-17 09:00:49',
      ],
      [
        'id' => 41,
        'title' => 'Dumbbell Wrist Curl',
        'slug' => 'dumbbell-wrist-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Dumbbell wrist curl adalah latihan isolasi untuk melatih otot lengan bawah bagian depan.',
        'image' => 'workouts/images/poBtGn1aTuO1qPVsiPtNN7hqgrfnLhavXgLzqPF1.png',
        'gif' => 'workouts/gifs/Iun5cvqez7wa2laTJXpBThlHLPzXUAkLWptvJcVJ.gif',
        'image_thumb' => 'workouts/images/thumbs/poBtGn1aTuO1qPVsiPtNN7hqgrfnLhavXgLzqPF1.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 09:06:29',
        'updated_at' => '2026-01-17 09:06:29',
      ],
      [
        'id' => 42,
        'title' => 'Barbell Skull Crusher',
        'slug' => 'barbell-skull-crusher',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Skull crusher adalah latihan isolasi untuk membangun kekuatan dan massa otot trisep.',
        'image' => 'workouts/images/ENDaT4lliptB4DOvA54tQgkA6YnJjSmvLzCiWdOs.png',
        'gif' => 'workouts/gifs/OJG2EVkutGeP7qtKitbsDxWAuncgU4zBh3J1HZQW.gif',
        'image_thumb' => 'workouts/images/thumbs/ENDaT4lliptB4DOvA54tQgkA6YnJjSmvLzCiWdOs.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 09:46:47',
        'updated_at' => '2026-01-22 08:56:36',
      ],
      [
        'id' => 43,
        'title' => 'Dumbbell Hammer Curl',
        'slug' => 'dumbbell-hammer-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Hammer curl melatih bisep dan lengan bawah dengan genggaman netral untuk ketebalan lengan.',
        'image' => 'workouts/images/axMpFAe54oGVfjGnAbbDMAEk8e8hK93adiUCuuB3.png',
        'gif' => 'workouts/gifs/bPzRGlkpLmPuk4rF9BkO0tLJkXWpnFnDyQTqm3qa.gif',
        'image_thumb' => 'workouts/images/thumbs/axMpFAe54oGVfjGnAbbDMAEk8e8hK93adiUCuuB3.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 09:59:10',
        'updated_at' => '2026-01-17 09:59:10',
      ],
      [
        'id' => 44,
        'title' => 'Cable Crunch',
        'slug' => 'cable-crunch',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Cable crunch adalah latihan perut dengan resistensi kabel untuk kontraksi yang lebih maksimal.',
        'image' => 'workouts/images/aVrMVk6JnI3nRjR72oIefOqPR2UK7cKVAzztWP6U.png',
        'gif' => 'workouts/gifs/DjYy1uCiaBaebu1N8sRHNyalVgl1C2shTeIbxCxD.gif',
        'image_thumb' => 'workouts/images/thumbs/aVrMVk6JnI3nRjR72oIefOqPR2UK7cKVAzztWP6U.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 20:58:04',
        'updated_at' => '2026-01-17 20:58:04',
      ],
      [
        'id' => 45,
        'title' => 'Captain’s Chair Leg Raises',
        'slug' => 'captains-chair-leg-raises',
        'type' => 'bodyweight',
        'workout_category_id' => 2,
        'description' => 'Captain’s Chair Leg Raises melatih otot perut bawah dan fleksor pinggul dengan kontrol penuh.',
        'image' => 'workouts/images/xwFQp3jgXTtKLx6qqe1OzrQisI7CXu4zsjbBmfWM.png',
        'gif' => 'workouts/gifs/gu4AgekxvlpvbtlK0tcZ0QNKNYgoBIfZqs85xnWl.gif',
        'image_thumb' => 'workouts/images/thumbs/xwFQp3jgXTtKLx6qqe1OzrQisI7CXu4zsjbBmfWM.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 21:10:50',
        'updated_at' => '2026-01-17 21:19:00',
      ],
      [
        'id' => 46,
        'title' => 'Close Grip Lat Pulldown',
        'slug' => 'close-grip-lat-pulldown',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Close grip lat pulldown menargetkan lat dan punggung tengah dengan pegangan sempit.',
        'image' => 'workouts/images/VvTUivRjFk1RtC0W5uGehrGsanBxZD41mOTpPMYo.png',
        'gif' => 'workouts/gifs/jVqtkKwkPlkIZu6UOI3jh6HQW8vfjXh8GRUCd9Im.gif',
        'image_thumb' => 'workouts/images/thumbs/VvTUivRjFk1RtC0W5uGehrGsanBxZD41mOTpPMYo.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 21:18:31',
        'updated_at' => '2026-01-17 21:20:01',
      ],
      [
        'id' => 47,
        'title' => 'Dumbbell Bench Press',
        'slug' => 'dumbbell-bench-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Dumbbell bench press melatih otot dada, bahu, dan trisep dengan rentang gerak lebih luas.',
        'image' => 'workouts/images/uFJIzI0Kr3zNvF9Mc8HLW9ylSGXyb86XN8enF4h5.png',
        'gif' => 'workouts/gifs/JLrqUDT539chTXAlm5XFCAfBHxX6caX2Ytgnlt2N.gif',
        'image_thumb' => 'workouts/images/thumbs/uFJIzI0Kr3zNvF9Mc8HLW9ylSGXyb86XN8enF4h5.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 21:39:29',
        'updated_at' => '2026-01-17 21:39:29',
      ],
      [
        'id' => 48,
        'title' => 'Dumbbell Incline Bench Press',
        'slug' => 'dumbbell-incline-bench-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Incline bench press menargetkan dada atas dengan bangku miring.',
        'image' => 'workouts/images/gLsVV3oZV7CPvVHpjwSEDKvFPVHGN2E0lCPQyzrr.png',
        'gif' => 'workouts/gifs/xrzosAYQLfeMFJmSjEvdY9NMq9WUugEaYVoH9xWz.gif',
        'image_thumb' => 'workouts/images/thumbs/gLsVV3oZV7CPvVHpjwSEDKvFPVHGN2E0lCPQyzrr.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 21:49:44',
        'updated_at' => '2026-01-17 21:49:44',
      ],
      [
        'id' => 49,
        'title' => 'Smith Machine Decline Bench Press',
        'slug' => 'smith-machine-decline-bench-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Decline bench press dengan Smith Machine menargetkan dada bawah dengan jalur gerak stabil.',
        'image' => 'workouts/images/2xgRvtXLyOwlsx8OiPx4naVFcScIg2kFRx4ISLio.png',
        'gif' => 'workouts/gifs/5t34e4ZzMoG8Oovp6RFONz0lJJkjDqtwRp0hH9mn.gif',
        'image_thumb' => 'workouts/images/thumbs/2xgRvtXLyOwlsx8OiPx4naVFcScIg2kFRx4ISLio.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 22:04:30',
        'updated_at' => '2026-01-17 22:04:30',
      ],
      [
        'id' => 50,
        'title' => 'Dumbbell Fly',
        'slug' => 'dumbbell-fly',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Dumbbell fly adalah latihan isolasi dada untuk fokus pada kontraksi otot pektoralis.',
        'image' => 'workouts/images/Kx5XqobT4ltnN03bY7XaDsWZqIhBgxHQh4XbWmRd.png',
        'gif' => 'workouts/gifs/hrdYmIdcGlcXGGssWHqaghDZt8knjFDgrqu6ME2j.gif',
        'image_thumb' => 'workouts/images/thumbs/Kx5XqobT4ltnN03bY7XaDsWZqIhBgxHQh4XbWmRd.webp',
        'video' => null,
        'difficulty' => null,
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 22:10:18',
        'updated_at' => '2026-01-17 22:10:18',
      ],

      [
        'id' => 51,
        'title' => 'Rope Triceps Pushdown',
        'slug' => 'rope-triceps-pushdown',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Rope Triceps Pushdown adalah latihan isolasi untuk otot trisep menggunakan mesin kabel dengan pegangan tali.',
        'image' => 'workouts/images/mJFo6WUcikdngaR4LIiRdBgX7TKMzvV7O67PSF66.png',
        'gif' => 'workouts/gifs/uE6omNU3qYkLpnVBSLyzeQ2qtacdFjWBQz3jFf50.gif',
        'image_thumb' => 'workouts/images/thumbs/mJFo6WUcikdngaR4LIiRdBgX7TKMzvV7O67PSF66.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 22:32:54',
        'updated_at' => '2026-01-17 22:32:54',
      ],
      [
        'id' => 52,
        'title' => 'Cable Rope Overhead Triceps Extension',
        'slug' => 'cable-rope-overhead-triceps-extension',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Cable overhead triceps extension adalah latihan isolasi trisep yang menargetkan terutama kepala panjang trisep dengan ketegangan kabel konstan.',
        'image' => 'workouts/images/lN0Ht9UefISdLFuo1MgdsaMQdRs3I9d8x2WSV8gJ.png',
        'gif' => 'workouts/gifs/60IHxuaYss53qajdhpTyhp6heBTUe0cRwrDp70Hy.gif',
        'image_thumb' => 'workouts/images/thumbs/lN0Ht9UefISdLFuo1MgdsaMQdRs3I9d8x2WSV8gJ.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 22:45:18',
        'updated_at' => '2026-01-19 01:43:03',
      ],
      [
        'id' => 53,
        'title' => 'Assisted Pull Up',
        'slug' => 'assisted-pull-up',
        'type' => 'assisted',
        'workout_category_id' => 2,
        'description' => 'Assisted pull-up membantu pemula membangun kekuatan punggung dan lengan menuju pull-up penuh.',
        'image' => 'workouts/images/iFO4iYFU47r1GfNFsMbbtzLpPpXVhMUcVRA0jGWk.png',
        'gif' => 'workouts/gifs/57EcrcwL7dzS9gqdUBxBiVVNnZqCYKSuizb8EO8l.gif',
        'image_thumb' => 'workouts/images/thumbs/iFO4iYFU47r1GfNFsMbbtzLpPpXVhMUcVRA0jGWk.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 23:02:25',
        'updated_at' => '2026-01-17 23:02:25',
      ],
      [
        'id' => 54,
        'title' => 'Dumbbell Row',
        'slug' => 'dumbbell-row',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Dumbbell row adalah latihan compound untuk punggung yang melatih lat, rhomboid, trapezius, dan bisep.',
        'image' => 'workouts/images/Wryl4mxzW6vj26xWulf2vXxjqhYYybPKEPGfnF6P.png',
        'gif' => 'workouts/gifs/3z2wcZBnIiHIEIYVVfskOK94WGtiHkQgUu5FZ3T9.gif',
        'image_thumb' => 'workouts/images/thumbs/Wryl4mxzW6vj26xWulf2vXxjqhYYybPKEPGfnF6P.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-17 23:20:50',
        'updated_at' => '2026-01-17 23:20:50',
      ],
      [
        'id' => 55,
        'title' => 'Yates Row / Reverse Barbell Bent Over Row',
        'slug' => 'yates-row',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Yates Row adalah variasi barbell row dengan pegangan supinasi dan posisi tubuh lebih tegak.',
        'image' => 'workouts/images/fB8vEtm4KVybok9z1WOVxltpFMqj4H7466DehGD9.png',
        'gif' => 'workouts/gifs/kvAzrBp5r2tBR59q7BnVPU14m9RJRQ8WtHOuGNy7.gif',
        'image_thumb' => 'workouts/images/thumbs/fB8vEtm4KVybok9z1WOVxltpFMqj4H7466DehGD9.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 02:02:24',
        'updated_at' => '2026-01-18 02:02:24',
      ],
      [
        'id' => 56,
        'title' => 'Dumbbell Curl',
        'slug' => 'dumbbell-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Dumbbell curl adalah latihan isolasi klasik untuk membangun kekuatan dan massa otot bisep.',
        'image' => 'workouts/images/Bxw4c2aqM8t5st6re9GcHxRfV8nLxkkFNxs1rOMQ.png',
        'gif' => 'workouts/gifs/Eaq5DAq89zIXOvsyNMX7FGSKGuVU5qVB4wPjCBvj.gif',
        'image_thumb' => 'workouts/images/thumbs/Bxw4c2aqM8t5st6re9GcHxRfV8nLxkkFNxs1rOMQ.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 02:05:38',
        'updated_at' => '2026-01-18 02:05:38',
      ],
      [
        'id' => 57,
        'title' => 'Lever Preacher Curl',
        'slug' => 'lever-preacher-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Lever preacher curl mengisolasi otot bisep secara maksimal dengan stabilitas mesin.',
        'image' => 'workouts/images/agFCKVoDl7jHdElfV8T8607ivuy9K1rQYiCxnd0Z.png',
        'gif' => 'workouts/gifs/ZexsdR7EDyKItOaNEkr8DYVa1FA8Jvd8wgrsdfKM.gif',
        'image_thumb' => 'workouts/images/thumbs/agFCKVoDl7jHdElfV8T8607ivuy9K1rQYiCxnd0Z.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 08:10:41',
        'updated_at' => '2026-01-18 08:10:41',
      ],
      [
        'id' => 58,
        'title' => 'Barbell Shoulder Press / Military Press',
        'slug' => 'barbell-shoulder-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Military press adalah latihan compound untuk membangun kekuatan bahu, trisep, dan core.',
        'image' => 'workouts/images/P8kg9pWXaDQWCzz5u8FybbIpHEPJX3Hzpu7UoYmY.png',
        'gif' => 'workouts/gifs/pJ9VUNAvJI7BaeZ3WyykXVn4X8eYB1QPLHqh2To9.gif',
        'image_thumb' => 'workouts/images/thumbs/P8kg9pWXaDQWCzz5u8FybbIpHEPJX3Hzpu7UoYmY.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 0.90,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 08:21:42',
        'updated_at' => '2026-01-22 22:04:30',
      ],
      [
        'id' => 59,
        'title' => 'Dumbbell Rear Delt Fly',
        'slug' => 'dumbbell-rear-delt-fly',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Rear delt fly melatih bahu belakang dan punggung atas untuk postur dan stabilitas bahu.',
        'image' => 'workouts/images/7ZOR2PStSh1OzZBrVDpXvpSOjGD2cf8HYnNymPsE.png',
        'gif' => 'workouts/gifs/CqGUOj4tGnZJhFqWB4t8sVIBdgZIKUPMVutYQpwl.gif',
        'image_thumb' => 'workouts/images/thumbs/7ZOR2PStSh1OzZBrVDpXvpSOjGD2cf8HYnNymPsE.webp',
        'video' => null,
        'difficulty' => null,
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 08:43:02',
        'updated_at' => '2026-01-18 08:43:02',
      ],
      [
        'id' => 60,
        'title' => 'Cable Upright Row',
        'slug' => 'cable-upright-row',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Cable upright row melatih bahu dan trapezius dengan ketegangan kabel konstan.',
        'image' => 'workouts/images/Wqy4DS2sP5HkoGpk69vbpoK3wclP1PgXlcJf0TEK.png',
        'gif' => 'workouts/gifs/qSCx1GO6vyouCjqaDtjgIrx1KrRtePemG7Efd981.gif',
        'image_thumb' => 'workouts/images/thumbs/Wqy4DS2sP5HkoGpk69vbpoK3wclP1PgXlcJf0TEK.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 08:55:00',
        'updated_at' => '2026-01-18 08:55:00',
      ],
      [
        'id' => 61,
        'title' => 'Hack Squat',
        'slug' => 'hack-squat',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Hack squat adalah latihan mesin untuk fokus membangun paha depan dengan stabilitas tinggi.',
        'image' => 'workouts/images/JXpyXXNICWNlonxuMloGH1eylhYrfU8va6CRKk4w.png',
        'gif' => 'workouts/gifs/YzH2zLIYZvTzB28pVrk283Df1tDhrjnv2fAdBg7q.gif',
        'image_thumb' => 'workouts/images/thumbs/JXpyXXNICWNlonxuMloGH1eylhYrfU8va6CRKk4w.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.10,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 09:12:01',
        'updated_at' => '2026-01-18 09:12:01',
      ],
      [
        'id' => 62,
        'title' => 'Standing Leg Curl',
        'slug' => 'standing-leg-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Standing leg curl melatih hamstring secara fungsional dengan posisi berdiri.',
        'image' => 'workouts/images/qLECHwJZ9csLkyBtxYPjrgDiltKq6Rxe4LZLT2Og.png',
        'gif' => 'workouts/gifs/nrrbJVYNHL193JEa8SVtMp6eaM3ueXdv4XOxtlAT.gif',
        'image_thumb' => 'workouts/images/thumbs/qLECHwJZ9csLkyBtxYPjrgDiltKq6Rxe4LZLT2Og.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 09:28:24',
        'updated_at' => '2026-01-18 09:39:26',
      ],
      [
        'id' => 63,
        'title' => 'Seated Leg Curl',
        'slug' => 'seated-leg-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Seated leg curl mengisolasi otot hamstring dengan posisi duduk dan kontrol penuh.',
        'image' => 'workouts/images/jCXdTdIBGyBCPRauG0Vc55fm4NuIXunpYfxqms5i.png',
        'gif' => 'workouts/gifs/ibY40INYneWu57CY202gIt2M8duTlywlCARUWap9.gif',
        'image_thumb' => 'workouts/images/thumbs/jCXdTdIBGyBCPRauG0Vc55fm4NuIXunpYfxqms5i.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 09:38:37',
        'updated_at' => '2026-01-18 09:38:37',
      ],
      [
        'id' => 64,
        'title' => 'Barbell Romanian Deadlift / RDL',
        'slug' => 'barbell-romanian-deadlift',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Romanian deadlift berfokus pada hip hinge untuk melatih hamstring dan glutes.',
        'image' => 'workouts/images/B9vWL99q3WbSMWTmYrCoYCeZ6Nobw5fjmvufW80M.png',
        'gif' => 'workouts/gifs/aZESx06CWIlOyouZGnjNkdMKXo1ECubdxpDCvMGC.gif',
        'image_thumb' => 'workouts/images/thumbs/B9vWL99q3WbSMWTmYrCoYCeZ6Nobw5fjmvufW80M.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.20,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 09:45:53',
        'updated_at' => '2026-01-22 08:07:29',
      ],
      [
        'id' => 65,
        'title' => 'Hip Abduction',
        'slug' => 'hip-abduction',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Hip abduction melatih otot paha luar dan stabilitas pinggul.',
        'image' => 'workouts/images/MELY9yBeTHxLiUf0KdY1AORIMSIlYOU4Ko04MKQ6.png',
        'gif' => 'workouts/gifs/dJCigtJZjHmm8jHq0IYFdOJPH8qj9FSmYpjcUbGb.gif',
        'image_thumb' => 'workouts/images/thumbs/MELY9yBeTHxLiUf0KdY1AORIMSIlYOU4Ko04MKQ6.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 09:51:41',
        'updated_at' => '2026-01-18 09:51:41',
      ],
      [
        'id' => 66,
        'title' => 'Hip Adduction',
        'slug' => 'hip-adduction',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Hip adduction mengisolasi otot paha dalam untuk stabilitas dan kekuatan pinggul.',
        'image' => 'workouts/images/zTkQ8v29MlBNbIgQPE0bSd4fjoMjLEhglNQBWKWz.png',
        'gif' => 'workouts/gifs/L9l7sgkQdqlGvW1qwFnqvqqITqlb90dg14zXtcWH.gif',
        'image_thumb' => 'workouts/images/thumbs/zTkQ8v29MlBNbIgQPE0bSd4fjoMjLEhglNQBWKWz.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-18 10:02:10',
        'updated_at' => '2026-01-18 10:02:10',
      ],
      [
        'id' => 67,
        'title' => 'Smith Machine Calf Raise',
        'slug' => 'smith-machine-calf-raise',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Smith machine calf raise mengisolasi otot betis dengan stabilitas mesin.',
        'image' => 'workouts/images/lJrSMlCZ5SxkaA10JAlbr5SRB4O7TwHWEF31wWr9.png',
        'gif' => 'workouts/gifs/5vRRwXv30dFZqFTQKLFA4gIHyLGoqESfb0xBaK9a.gif',
        'image_thumb' => 'workouts/images/thumbs/lJrSMlCZ5SxkaA10JAlbr5SRB4O7TwHWEF31wWr9.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 01:21:42',
        'updated_at' => '2026-01-19 01:21:42',
      ],
      [
        'id' => 68,
        'title' => 'Reverse Grip Ez-Bar Curls',
        'slug' => 'reverse-grip-ez-bar-curls',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Reverse grip EZ-bar curls menargetkan brachialis dan lengan bawah.',
        'image' => 'workouts/images/67ke9lMJrxDKSCwP0Zkbk4iM98xYkGYxFJkoTbgq.png',
        'gif' => 'workouts/gifs/vBLmbFCxIpbgPsI7IfDp38PqvnytUK4P4ll4Er9P.gif',
        'image_thumb' => 'workouts/images/thumbs/67ke9lMJrxDKSCwP0Zkbk4iM98xYkGYxFJkoTbgq.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.50,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 01:29:16',
        'updated_at' => '2026-01-19 01:30:12',
      ],
      [
        'id' => 69,
        'title' => 'Incline Dumbbell Curls',
        'slug' => 'incline-dumbbell-curls',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Incline dumbbell curls menekankan peregangan dan puncak bisep.',
        'image' => 'workouts/images/6M9BMulOE4ZSB2mbbIz6U6w96lAr4DrdhPXlDTLA.png',
        'gif' => 'workouts/gifs/QY94MQGJTuMiI4szrwHOsBjvtPapehtmOMjfYqXI.gif',
        'image_thumb' => 'workouts/images/thumbs/6M9BMulOE4ZSB2mbbIz6U6w96lAr4DrdhPXlDTLA.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 01:38:04',
        'updated_at' => '2026-01-19 01:38:04',
      ],
      [
        'id' => 70,
        'title' => 'Barbell Wrist Curl',
        'slug' => 'barbell-wrist-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Barbell wrist curl melatih fleksor pergelangan tangan untuk kekuatan grip.',
        'image' => 'workouts/images/ITIFqxIb6fBbev5TDzqeu9X2srnE0B0848vJBIFw.png',
        'gif' => 'workouts/gifs/L5ebzmWXU86lyTFl9wVCfG0Dr5Bds4bSlUxzUzIt.gif',
        'image_thumb' => 'workouts/images/thumbs/ITIFqxIb6fBbev5TDzqeu9X2srnE0B0848vJBIFw.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 01:49:48',
        'updated_at' => '2026-01-19 01:49:48',
      ],

      [
        'id' => 71,
        'title' => 'Hanging Leg Raise',
        'slug' => 'hanging-leg-raise',
        'type' => 'bodyweight',
        'workout_category_id' => 5,
        'description' => 'Hanging leg raise adalah latihan inti untuk memperkuat perut bawah dan fleksor pinggul dengan menggantung di palang.',
        'image' => 'workouts/images/ytEAQzP9rUsW4cn0E7mcVQyeJqZzIVv9Fdcpwd9O.png',
        'gif' => 'workouts/gifs/jPQCuL2R0LOuExcmBUAFtTzDUYqPk5Rj17rNXArh.gif',
        'image_thumb' => 'workouts/images/thumbs/ytEAQzP9rUsW4cn0E7mcVQyeJqZzIVv9Fdcpwd9O.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'isolation',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 02:01:22',
        'updated_at' => '2026-01-19 02:01:22',
      ],
      [
        'id' => 72,
        'title' => 'Kettlebell Russian Twist',
        'slug' => 'kettlebell-russian-twist',
        'type' => 'machine',
        'workout_category_id' => 5,
        'description' => 'Russian twist dengan kettlebell untuk melatih otot core dan obliques melalui rotasi tubuh.',
        'image' => 'workouts/images/q5RzSAANUlcYSin60Svf6cRudVoksas3hl9ucuXa.png',
        'gif' => 'workouts/gifs/7epZNmWAbjtXYNHuMfFJ78BlFs872PGM3d6iM3rA.gif',
        'image_thumb' => 'workouts/images/thumbs/q5RzSAANUlcYSin60Svf6cRudVoksas3hl9ucuXa.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 02:04:49',
        'updated_at' => '2026-01-19 02:04:49',
      ],
      [
        'id' => 73,
        'title' => 'Hammer Strength Chest Press',
        'slug' => 'hammer-strength-chest-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Hammer Strength chest press melatih dada, bahu depan, dan trisep dengan stabilitas mesin.',
        'image' => 'workouts/images/jrKBYPdkvAFyABIu8X3J3QOiZJipXSkZTmtUy34c.png',
        'gif' => 'workouts/gifs/unUfR9fBhYROKQLOQAqiwc66zn7FrSLfKdrsLEVQ.gif',
        'image_thumb' => 'workouts/images/thumbs/jrKBYPdkvAFyABIu8X3J3QOiZJipXSkZTmtUy34c.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 02:09:34',
        'updated_at' => '2026-01-19 02:09:34',
      ],
      [
        'id' => 74,
        'title' => 'Lever Chest Press',
        'slug' => 'lever-chest-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Lever chest press adalah latihan mesin untuk membangun kekuatan dan massa otot dada.',
        'image' => 'workouts/images/i0RCeamiSAZxUkFxRVuLqLXGgfIJyeFsn1JAqun3.png',
        'gif' => 'workouts/gifs/UfO5g3dfJiCM284GocS7fuyQ1KCJJQv5gZoFujtI.gif',
        'image_thumb' => 'workouts/images/thumbs/i0RCeamiSAZxUkFxRVuLqLXGgfIJyeFsn1JAqun3.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 02:22:33',
        'updated_at' => '2026-01-19 02:22:33',
      ],
      [
        'id' => 75,
        'title' => 'Barbell Decline Bench Press',
        'slug' => 'barbell-decline-bench-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Decline bench press menargetkan dada bawah, trisep, dan bahu depan.',
        'image' => 'workouts/images/2GphTwrPtKuJtV4BuBlLhzPg5QRvNd7AyF2oB9F5.png',
        'gif' => 'workouts/gifs/vIFhZXX0H9bs8MqRFgPFpleGJQGQacgbXLdADNHv.gif',
        'image_thumb' => 'workouts/images/thumbs/2GphTwrPtKuJtV4BuBlLhzPg5QRvNd7AyF2oB9F5.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.10,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 02:29:45',
        'updated_at' => '2026-01-19 02:29:45',
      ],
      [
        'id' => 76,
        'title' => 'Dumbbell Pullover',
        'slug' => 'dumbbell-pullover',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Dumbbell pullover melatih dada dan punggung dengan gerakan ekstensi bahu.',
        'image' => 'workouts/images/qmviERLPaDiWRvJXJqUUKCFI3z0jURnQ5Ag7PyOy.png',
        'gif' => 'workouts/gifs/0sOp7jTmqc7xKEe6xD8pigmkRltpwVJwykRfnEE9.gif',
        'image_thumb' => 'workouts/images/thumbs/qmviERLPaDiWRvJXJqUUKCFI3z0jURnQ5Ag7PyOy.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 02:38:39',
        'updated_at' => '2026-01-19 02:38:39',
      ],
      [
        'id' => 77,
        'title' => 'Close Grip Bench Press',
        'slug' => 'close-grip-bench-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Close grip bench press memfokuskan beban pada trisep dan kekuatan pressing.',
        'image' => 'workouts/images/uKoFzN5cf4DiNZHx5i4iviy85n086PkzYB8onYWc.png',
        'gif' => 'workouts/gifs/IephexvtvFS9iKauBA2O29t7wI9R9uzsfvRsN8S0.gif',
        'image_thumb' => 'workouts/images/thumbs/uKoFzN5cf4DiNZHx5i4iviy85n086PkzYB8onYWc.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.90,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 02:43:41',
        'updated_at' => '2026-01-19 02:43:41',
      ],
      [
        'id' => 78,
        'title' => 'Ez-Bar Seated Triceps Extension',
        'slug' => 'ez-bar-seated-triceps-extension',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Seated triceps extension menggunakan EZ-bar untuk menargetkan kepala panjang trisep.',
        'image' => 'workouts/images/aKLqKD2dHNqXj7Ar8bTi1xe4lpDyJyQHd2w45yaK.png',
        'gif' => 'workouts/gifs/bjCEcI1upE7hpQ2blp92bMDSvJVj1gqms90Ir3Id.gif',
        'image_thumb' => 'workouts/images/thumbs/aKLqKD2dHNqXj7Ar8bTi1xe4lpDyJyQHd2w45yaK.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'isolation',
        'difficulty_factor' => 0.50,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 02:54:24',
        'updated_at' => '2026-01-19 02:54:24',
      ],
      [
        'id' => 79,
        'title' => 'Lat Pulldown',
        'slug' => 'lat-pulldown',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Lat pulldown melatih punggung atas dan latissimus dorsi dengan gerakan vertikal.',
        'image' => 'workouts/images/Ny1ZxeyScQEEqdGBEfJHdjOxqkIRjGxNj80zLwOM.png',
        'gif' => 'workouts/gifs/tnVy5k0ZZuFOHlVLCKkfsDp0VVUKmNS4TkFvxp4u.gif',
        'image_thumb' => 'workouts/images/thumbs/Ny1ZxeyScQEEqdGBEfJHdjOxqkIRjGxNj80zLwOM.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 03:01:03',
        'updated_at' => '2026-01-19 03:01:03',
      ],
      [
        'id' => 80,
        'title' => 'Hammer Strength Iso-Lateral Row',
        'slug' => 'hammer-strength-iso-lateral-row',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Iso-lateral row melatih punggung dengan gerakan independen kiri dan kanan.',
        'image' => 'workouts/images/7yIcfJRV6jIkQ6Tbk3cJgXnECJzUIxOoXUBexTXX.png',
        'gif' => 'workouts/gifs/AhSAyOkuJ9eo4jqqYKQ8oXhUzS9vhcAGu61wozjr.gif',
        'image_thumb' => 'workouts/images/thumbs/7yIcfJRV6jIkQ6Tbk3cJgXnECJzUIxOoXUBexTXX.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 08:18:31',
        'updated_at' => '2026-01-19 08:18:31',
      ],
      [
        'id' => 81,
        'title' => 'One-arm Chest Supported Row Machine',
        'slug' => 'one-arm-chest-supported-row-machine',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Chest supported row satu tangan untuk isolasi punggung dan koreksi imbalance.',
        'image' => 'workouts/images/MffVaeqaPlvWgWXTHY92DPacJo3cU4b3x0FkHiCW.png',
        'gif' => 'workouts/gifs/8FMsaS0Vn1N2n20O3IQScDboTBwk5ZvmR45LZymI.gif',
        'image_thumb' => 'workouts/images/thumbs/MffVaeqaPlvWgWXTHY92DPacJo3cU4b3x0FkHiCW.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 08:24:45',
        'updated_at' => '2026-01-19 08:24:45',
      ],
      [
        'id' => 82,
        'title' => 'Barbell Curl',
        'slug' => 'barbell-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Barbell curl adalah latihan dasar untuk membangun kekuatan dan massa bisep.',
        'image' => 'workouts/images/DgSfgZWjOQXMynZIcirZtjS72kdirFKs49d8uQxM.png',
        'gif' => 'workouts/gifs/vyxMoS2LN3MVeUhutqqsUFHCoUJd4Jvptzm0gMZG.gif',
        'image_thumb' => 'workouts/images/thumbs/DgSfgZWjOQXMynZIcirZtjS72kdirFKs49d8uQxM.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 08:42:26',
        'updated_at' => '2026-01-19 08:42:26',
      ],
      [
        'id' => 83,
        'title' => 'Landmine Press',
        'slug' => 'landmine-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Landmine press adalah latihan bahu dan trisep dengan jalur diagonal.',
        'image' => 'workouts/images/MYJDFyiJumOUGlCBAGY6ujpCNk1YwnsbvfWhehiy.png',
        'gif' => 'workouts/gifs/fGQSzj0ugoxTSv5w88mqjKUx2kZ0DhzZ4vUW4axV.gif',
        'image_thumb' => 'workouts/images/thumbs/MYJDFyiJumOUGlCBAGY6ujpCNk1YwnsbvfWhehiy.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.70,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 08:51:58',
        'updated_at' => '2026-01-19 08:51:58',
      ],
      [
        'id' => 84,
        'title' => 'Reverse Pec Deck Fly',
        'slug' => 'reverse-pec-deck-fly',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Reverse pec deck fly melatih bahu belakang dan punggung atas.',
        'image' => 'workouts/images/AvfQd2KwCQRjAknqP1WzL5v6o4jSgCWUXcI4vWoi.png',
        'gif' => 'workouts/gifs/jprfx2FTdGytaqiITWUxDhJDjEGcXLwaooP9mpd0.gif',
        'image_thumb' => 'workouts/images/thumbs/AvfQd2KwCQRjAknqP1WzL5v6o4jSgCWUXcI4vWoi.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 09:00:34',
        'updated_at' => '2026-01-19 09:00:34',
      ],
      [
        'id' => 85,
        'title' => 'Barbell Front Raise',
        'slug' => 'barbell-front-raise',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Barbell front raise menargetkan deltoid anterior dengan beban lebih besar.',
        'image' => 'workouts/images/4rEcFsZKXUi7e4dv9yg8rQRhGyKvP1fehcAY2pFL.png',
        'gif' => 'workouts/gifs/KzdoCG5zgUFdXnpIcIpVmcvENCfEjBX5D7gQDjZU.gif',
        'image_thumb' => 'workouts/images/thumbs/4rEcFsZKXUi7e4dv9yg8rQRhGyKvP1fehcAY2pFL.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-19 09:09:32',
        'updated_at' => '2026-01-19 09:09:32',
      ],
      [
        'id' => 86,
        'title' => 'Dumbbell Shrug',
        'slug' => 'dumbbell-shrug',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Dumbbell shrug mengisolasi otot trapezius dengan gerakan angkat bahu.',
        'image' => 'workouts/images/dbp1CyMY3SKHrWydCyeLlpOISFSEK1PikWrdowax.png',
        'gif' => 'workouts/gifs/iBPuj3WL9F5vjTSDyY7Q2QZGa2IIMoF02nzedbEu.gif',
        'image_thumb' => 'workouts/images/thumbs/dbp1CyMY3SKHrWydCyeLlpOISFSEK1PikWrdowax.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 07:32:16',
        'updated_at' => '2026-01-22 07:32:16',
      ],
      [
        'id' => 87,
        'title' => 'Front Squat',
        'slug' => 'front-squat',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Front squat menekankan quadriceps dan postur tegak.',
        'image' => 'workouts/images/Ov1MgjF3z24NlS8b2vmQLLSlwOrdBOy6Dle3F2T7.png',
        'gif' => 'workouts/gifs/LzN6aCKrtVIld9fNbv71ubJwDZj3Jv2DU1oukPO4.gif',
        'image_thumb' => 'workouts/images/thumbs/Ov1MgjF3z24NlS8b2vmQLLSlwOrdBOy6Dle3F2T7.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 1.10,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 07:38:35',
        'updated_at' => '2026-01-22 07:38:35',
      ],
      [
        'id' => 88,
        'title' => 'Dumbbell Bulgarian Split Squat',
        'slug' => 'dumbbell-bulgarian-split-squat',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Bulgarian split squat melatih kaki secara unilateral dan keseimbangan.',
        'image' => 'workouts/images/HHp4IowcIEnnfA3nyd3LH5sDl8Kmm1YLweuTrPuz.png',
        'gif' => 'workouts/gifs/88TW3sw5woNeNa9iLu8tVODtNTbXyBSq9WDqonnm.gif',
        'image_thumb' => 'workouts/images/thumbs/HHp4IowcIEnnfA3nyd3LH5sDl8Kmm1YLweuTrPuz.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 08:05:48',
        'updated_at' => '2026-01-22 08:05:48',
      ],
      [
        'id' => 89,
        'title' => 'Standing Calf Raise',
        'slug' => 'standing-calf-raise',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Standing calf raise melatih otot betis gastrocnemius.',
        'image' => 'workouts/images/hni6XfqQUmQwHSybdnYsSS04vl8KNXWjRFFRs41s.png',
        'gif' => 'workouts/gifs/BLbjGQFLlllTytRUwcdDw2eTnesatNk5YNBIx4Mj.gif',
        'image_thumb' => 'workouts/images/thumbs/hni6XfqQUmQwHSybdnYsSS04vl8KNXWjRFFRs41s.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 08:49:09',
        'updated_at' => '2026-01-22 08:49:09',
      ],
      [
        'id' => 90,
        'title' => 'Dumbbell Skull Crusher',
        'slug' => 'dumbbell-skull-crusher',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Dumbbell skull crusher mengisolasi trisep dengan kontrol unilateral.',
        'image' => 'workouts/images/pz73naWvSMjIJGJd70B3Q2E18yehUBvWpjKL3n1J.png',
        'gif' => 'workouts/gifs/I6s6g6RYiTreiML2e94UqPD8y6s4d50sppj0l402.gif',
        'image_thumb' => 'workouts/images/thumbs/pz73naWvSMjIJGJd70B3Q2E18yehUBvWpjKL3n1J.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 09:02:42',
        'updated_at' => '2026-01-22 09:02:42',
      ],
      [
        'id' => 91,
        'title' => 'Cable Knee Crunch',
        'slug' => 'cable-knee-crunch',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Cable knee crunch melatih otot perut dengan resistensi kabel konstan.',
        'image' => 'workouts/images/Ma1PeDraTjxm83iFdP4ckrCY16aAZowuZcZbR1kV.png',
        'gif' => 'workouts/gifs/6h1O6DMY6o3hE2O37QLXetnw8y1pj99pW8AOYp2i.gif',
        'image_thumb' => 'workouts/images/thumbs/Ma1PeDraTjxm83iFdP4ckrCY16aAZowuZcZbR1kV.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 09:20:46',
        'updated_at' => '2026-01-22 09:20:46',
      ],
      [
        'id' => 92,
        'title' => 'Sit Up',
        'slug' => 'sit-up',
        'type' => 'bodyweight',
        'workout_category_id' => 2,
        'description' => 'Sit up adalah latihan klasik untuk memperkuat otot perut.',
        'image' => 'workouts/images/ogM7N3ujDaeaJLamKpJsC7HIxwQB5QedhuNIAzZw.png',
        'gif' => 'workouts/gifs/VK2aExdY5iuGRzFlMNs0erHE2K7Ubuhts5Eor1rn.gif',
        'image_thumb' => 'workouts/images/thumbs/ogM7N3ujDaeaJLamKpJsC7HIxwQB5QedhuNIAzZw.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'isolation',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 09:27:45',
        'updated_at' => '2026-01-22 09:27:45',
      ],
      [
        'id' => 93,
        'title' => 'Smith Machine Bench Press',
        'slug' => 'smith-machine-bench-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Smith bench press memberikan stabilitas tinggi untuk latihan dada.',
        'image' => 'workouts/images/AT5MOt3NWBcCa5R24ddPvk96NPFpWOsDHuL3vKaR.png',
        'gif' => 'workouts/gifs/afnEiEYQYZY7hD1jKlLsO6BYUeHhUINt8896KtmJ.gif',
        'image_thumb' => 'workouts/images/thumbs/AT5MOt3NWBcCa5R24ddPvk96NPFpWOsDHuL3vKaR.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.10,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 09:44:25',
        'updated_at' => '2026-01-22 09:44:25',
      ],
      [
        'id' => 94,
        'title' => 'Smith Machine Incline Bench Press',
        'slug' => 'smith-machine-incline-bench-press',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Incline bench press di Smith Machine menargetkan dada atas.',
        'image' => 'workouts/images/o1l0DZr5vWeUUmCuQa1aeHi1nky8es8r5ceI6MwB.png',
        'gif' => 'workouts/gifs/anXSKE8KEX4HJjGELfzPb9J3dJb3yxsiUeZUnoQk.gif',
        'image_thumb' => 'workouts/images/thumbs/o1l0DZr5vWeUUmCuQa1aeHi1nky8es8r5ceI6MwB.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.10,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 20:48:53',
        'updated_at' => '2026-01-22 20:48:53',
      ],
      [
        'id' => 95,
        'title' => 'Seated Dip Machine',
        'slug' => 'seated-dip-machine',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Seated dip machine mengisolasi trisep dengan stabilitas tinggi.',
        'image' => 'workouts/images/DzL4XxI122w8J2cubJ32LA1XmflS4hoMOQGIIrJx.png',
        'gif' => 'workouts/gifs/3HbLzRoAxXeH6bZA04ndTteORvKpNRlpTyZweaMM.gif',
        'image_thumb' => 'workouts/images/thumbs/DzL4XxI122w8J2cubJ32LA1XmflS4hoMOQGIIrJx.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 21:17:02',
        'updated_at' => '2026-01-22 21:17:02',
      ],
      [
        'id' => 96,
        'title' => 'Tricep Overhead Extension',
        'slug' => 'tricep-overhead-extension',
        'type' => 'machine',
        'workout_category_id' => 1,
        'description' => 'Overhead extension menargetkan kepala panjang trisep.',
        'image' => 'workouts/images/rBbIDuBPjnzLsKwfhnoExBt0VYaBVIQBQiopb7Uk.png',
        'gif' => 'workouts/gifs/P063wL7ipMKK1OxsnukeYqS7wIYv4cEtTYNWvaaK.gif',
        'image_thumb' => 'workouts/images/thumbs/rBbIDuBPjnzLsKwfhnoExBt0VYaBVIQBQiopb7Uk.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.40,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 21:32:06',
        'updated_at' => '2026-01-22 21:32:06',
      ],
      [
        'id' => 97,
        'title' => 'Pull Up',
        'slug' => 'pull-up',
        'type' => 'bodyweight',
        'workout_category_id' => 2,
        'description' => 'Pull-up adalah latihan bodyweight utama untuk punggung dan lengan.',
        'image' => 'workouts/images/XcYKM2A2KU8LBBjao40ETNXACejSBsexj4ri3eqX.png',
        'gif' => 'workouts/gifs/neSDHvPFOMEGZg04pRaelfkd2cYRjUdnBs2lmctG.gif',
        'image_thumb' => 'workouts/images/thumbs/XcYKM2A2KU8LBBjao40ETNXACejSBsexj4ri3eqX.webp',
        'video' => null,
        'difficulty' => 'intermediate',
        'movement' => 'compound',
        'difficulty_factor' => 1.00,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 21:36:59',
        'updated_at' => '2026-01-23 02:25:59',
      ],
      [
        'id' => 98,
        'title' => 'Landmine Row',
        'slug' => 'landmine-row',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Landmine row adalah latihan punggung dengan barbel tertambat.',
        'image' => 'workouts/images/3NPmv3IqcDtFPHW7oaipDx97UYfU1wiDAVyYD6GW.png',
        'gif' => 'workouts/gifs/RiOzLThYZH4e8ieJCQHptcf0XCAzYfglcdbfgMAn.gif',
        'image_thumb' => 'workouts/images/thumbs/3NPmv3IqcDtFPHW7oaipDx97UYfU1wiDAVyYD6GW.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 21:43:57',
        'updated_at' => '2026-01-22 21:43:57',
      ],
      [
        'id' => 99,
        'title' => 'T-Bar Row',
        'slug' => 't-bar-row',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'T-bar row membangun ketebalan punggung dan kekuatan tarikan.',
        'image' => 'workouts/images/m6aphrLltpEe2YPAWcAP6XGBWNoUInsUuo2Kk9gE.png',
        'gif' => 'workouts/gifs/K6BGByuYpqwcHCJNi50mQcy3nLcYWE8OuRzUs2c9.gif',
        'image_thumb' => 'workouts/images/thumbs/m6aphrLltpEe2YPAWcAP6XGBWNoUInsUuo2Kk9gE.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.10,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 21:47:34',
        'updated_at' => '2026-01-22 21:47:34',
      ],
      [
        'id' => 100,
        'title' => 'Single-arm Cable Lateral Raise',
        'slug' => 'single-arm-cable-lateral-raise',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Cable lateral raise satu tangan untuk bahu samping dengan tegangan konstan.',
        'image' => 'workouts/images/oPb9FNTJmewM9Q4FWyRj14LDB3hj1R7Ihde858Lp.png',
        'gif' => 'workouts/gifs/IjetVD7Ia4fqfpbSwTWLiWwvKxPBZT7wSx7sUNeQ.gif',
        'image_thumb' => 'workouts/images/thumbs/oPb9FNTJmewM9Q4FWyRj14LDB3hj1R7Ihde858Lp.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.25,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 21:53:38',
        'updated_at' => '2026-01-22 21:55:40',
      ],
      [
        'id' => 101,
        'title' => 'Cable Face Pull',
        'slug' => 'cable-face-pull',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Cable face pull memperkuat bahu belakang dan rotator cuff.',
        'image' => 'workouts/images/3C43rbKKzx7Mozr7pJVH9RfhrAtdaXQXKKPJwxHx.png',
        'gif' => 'workouts/gifs/bRSU4Qdic0K7ViXVm05hVpcQizZHidekc5NjcCVe.gif',
        'image_thumb' => 'workouts/images/thumbs/3C43rbKKzx7Mozr7pJVH9RfhrAtdaXQXKKPJwxHx.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 0.80,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 22:00:50',
        'updated_at' => '2026-01-22 22:00:50',
      ],
      [
        'id' => 102,
        'title' => 'Dumbbell Lunge',
        'slug' => 'dumbbell-lunge',
        'type' => 'machine',
        'workout_category_id' => 3,
        'description' => 'Dumbbell lunge melatih kekuatan kaki dan keseimbangan.',
        'image' => 'workouts/images/7glMMTkDX0ko7x3mfe1ds2hKRu9OpwehCaJbb0Tz.png',
        'gif' => 'workouts/gifs/oS4ZsfShXqEkv9tItyAwYKCyr3lN6DpEW4wvDMzv.gif',
        'image_thumb' => 'workouts/images/thumbs/7glMMTkDX0ko7x3mfe1ds2hKRu9OpwehCaJbb0Tz.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'compound',
        'difficulty_factor' => 1.10,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-22 22:48:11',
        'updated_at' => '2026-01-22 22:48:11',
      ],
      [
        'id' => 103,
        'title' => 'Ez-Bar Preacher Curl',
        'slug' => 'ez-bar-preacher-curl',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'EZ-bar preacher curl mengisolasi bisep dengan bantalan preacher.',
        'image' => 'workouts/images/6CjldOqDhFKNdYiBLrE4SHiWd9V6RoLDWk4ivJwM.png',
        'gif' => 'workouts/gifs/Lcd2VO08JqiDObcxcJjKHhDj2NAQZSLXUHsSqh9d.gif',
        'image_thumb' => 'workouts/images/thumbs/6CjldOqDhFKNdYiBLrE4SHiWd9V6RoLDWk4ivJwM.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-23 01:39:26',
        'updated_at' => '2026-01-23 01:39:26',
      ],
      [
        'id' => 104,
        'title' => 'Bayesian Cable Curls',
        'slug' => 'bayesian-cable-curls',
        'type' => 'machine',
        'workout_category_id' => 2,
        'description' => 'Bayesian cable curl menekankan peregangan maksimal pada bisep.',
        'image' => 'workouts/images/4xWI31MDTc82kMQBTt8PZ2CniGtFIErFHOFneL3A.png',
        'gif' => 'workouts/gifs/2OW26R3S4Ya1Wli4SGiL1e1qLvQBJ4CwSxXVpCRf.gif',
        'image_thumb' => 'workouts/images/thumbs/4xWI31MDTc82kMQBTt8PZ2CniGtFIErFHOFneL3A.webp',
        'video' => null,
        'difficulty' => 'beginner',
        'movement' => 'isolation',
        'difficulty_factor' => 0.60,
        'is_active' => 1,
        'order' => 0,
        'created_at' => '2026-01-23 01:50:13',
        'updated_at' => '2026-01-23 01:50:13',
      ],
    ]);
  }
}
