<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkoutContextWorkoutSeeder extends Seeder
{
  public function run(): void
  {
    DB::table('workout_context_workout')->insert([
      ['id' => 1, 'workout_id' => 1, 'workout_context_id' => 1],
      ['id' => 2, 'workout_id' => 2, 'workout_context_id' => 1],
      ['id' => 3, 'workout_id' => 3, 'workout_context_id' => 1],
      ['id' => 4, 'workout_id' => 4, 'workout_context_id' => 1],
      ['id' => 8, 'workout_id' => 6, 'workout_context_id' => 1],
      ['id' => 9, 'workout_id' => 7, 'workout_context_id' => 2],
      ['id' => 10, 'workout_id' => 8, 'workout_context_id' => 2],
      ['id' => 11, 'workout_id' => 9, 'workout_context_id' => 2],
      ['id' => 12, 'workout_id' => 10, 'workout_context_id' => 1],
      ['id' => 13, 'workout_id' => 11, 'workout_context_id' => 2],
      ['id' => 14, 'workout_id' => 12, 'workout_context_id' => 1],
      ['id' => 15, 'workout_id' => 13, 'workout_context_id' => 2],
      ['id' => 16, 'workout_id' => 14, 'workout_context_id' => 1],
      ['id' => 17, 'workout_id' => 15, 'workout_context_id' => 1],
      ['id' => 18, 'workout_id' => 16, 'workout_context_id' => 1],
      ['id' => 19, 'workout_id' => 17, 'workout_context_id' => 1],
      ['id' => 20, 'workout_id' => 18, 'workout_context_id' => 1],
      ['id' => 21, 'workout_id' => 18, 'workout_context_id' => 2],
      ['id' => 22, 'workout_id' => 18, 'workout_context_id' => 3],
      ['id' => 23, 'workout_id' => 18, 'workout_context_id' => 4],
      ['id' => 24, 'workout_id' => 19, 'workout_context_id' => 1],
      ['id' => 25, 'workout_id' => 19, 'workout_context_id' => 2],
      ['id' => 26, 'workout_id' => 19, 'workout_context_id' => 3],
      ['id' => 27, 'workout_id' => 19, 'workout_context_id' => 4],
      ['id' => 28, 'workout_id' => 20, 'workout_context_id' => 1],
      ['id' => 29, 'workout_id' => 21, 'workout_context_id' => 1],
      ['id' => 30, 'workout_id' => 22, 'workout_context_id' => 1],
      ['id' => 31, 'workout_id' => 23, 'workout_context_id' => 1],
      ['id' => 32, 'workout_id' => 24, 'workout_context_id' => 1],
      ['id' => 33, 'workout_id' => 25, 'workout_context_id' => 1],
      ['id' => 34, 'workout_id' => 26, 'workout_context_id' => 1],
      ['id' => 35, 'workout_id' => 27, 'workout_context_id' => 1],
      ['id' => 36, 'workout_id' => 28, 'workout_context_id' => 1],
      ['id' => 37, 'workout_id' => 29, 'workout_context_id' => 1],
      ['id' => 38, 'workout_id' => 30, 'workout_context_id' => 1],
      ['id' => 39, 'workout_id' => 31, 'workout_context_id' => 1],
      ['id' => 40, 'workout_id' => 32, 'workout_context_id' => 1],
      ['id' => 41, 'workout_id' => 33, 'workout_context_id' => 1],
      ['id' => 42, 'workout_id' => 34, 'workout_context_id' => 1],
      ['id' => 43, 'workout_id' => 35, 'workout_context_id' => 1],
      ['id' => 44, 'workout_id' => 36, 'workout_context_id' => 1],
      ['id' => 45, 'workout_id' => 37, 'workout_context_id' => 1],
      ['id' => 46, 'workout_id' => 38, 'workout_context_id' => 1],
      ['id' => 47, 'workout_id' => 39, 'workout_context_id' => 1],
      ['id' => 48, 'workout_id' => 40, 'workout_context_id' => 1],
      ['id' => 49, 'workout_id' => 41, 'workout_context_id' => 1],
      ['id' => 50, 'workout_id' => 42, 'workout_context_id' => 1],
      ['id' => 51, 'workout_id' => 43, 'workout_context_id' => 1],
      ['id' => 52, 'workout_id' => 44, 'workout_context_id' => 1],
      ['id' => 53, 'workout_id' => 45, 'workout_context_id' => 1],
      ['id' => 54, 'workout_id' => 45, 'workout_context_id' => 2],
      ['id' => 55, 'workout_id' => 46, 'workout_context_id' => 1],
      ['id' => 56, 'workout_id' => 47, 'workout_context_id' => 1],
      ['id' => 57, 'workout_id' => 48, 'workout_context_id' => 1],
      ['id' => 58, 'workout_id' => 49, 'workout_context_id' => 1],
      ['id' => 59, 'workout_id' => 50, 'workout_context_id' => 1],
      ['id' => 60, 'workout_id' => 51, 'workout_context_id' => 1],
      ['id' => 61, 'workout_id' => 52, 'workout_context_id' => 1],
      ['id' => 62, 'workout_id' => 53, 'workout_context_id' => 1],
      ['id' => 63, 'workout_id' => 54, 'workout_context_id' => 1],
      ['id' => 64, 'workout_id' => 55, 'workout_context_id' => 1],
      ['id' => 65, 'workout_id' => 56, 'workout_context_id' => 1],
      ['id' => 66, 'workout_id' => 57, 'workout_context_id' => 1],
      ['id' => 67, 'workout_id' => 58, 'workout_context_id' => 1],
      ['id' => 68, 'workout_id' => 59, 'workout_context_id' => 1],
      ['id' => 69, 'workout_id' => 60, 'workout_context_id' => 1],
      ['id' => 70, 'workout_id' => 61, 'workout_context_id' => 1],
      ['id' => 71, 'workout_id' => 62, 'workout_context_id' => 1],
      ['id' => 72, 'workout_id' => 63, 'workout_context_id' => 1],
      ['id' => 73, 'workout_id' => 64, 'workout_context_id' => 1],
      ['id' => 74, 'workout_id' => 65, 'workout_context_id' => 1],
      ['id' => 75, 'workout_id' => 66, 'workout_context_id' => 1],
      ['id' => 76, 'workout_id' => 67, 'workout_context_id' => 1],
      ['id' => 77, 'workout_id' => 68, 'workout_context_id' => 1],
      ['id' => 78, 'workout_id' => 69, 'workout_context_id' => 1],
      ['id' => 79, 'workout_id' => 70, 'workout_context_id' => 1],
      ['id' => 80, 'workout_id' => 71, 'workout_context_id' => 1],
      ['id' => 81, 'workout_id' => 71, 'workout_context_id' => 2],
      ['id' => 82, 'workout_id' => 71, 'workout_context_id' => 3],
      ['id' => 83, 'workout_id' => 71, 'workout_context_id' => 4],
      ['id' => 84, 'workout_id' => 72, 'workout_context_id' => 1],
      ['id' => 85, 'workout_id' => 72, 'workout_context_id' => 2],
      ['id' => 86, 'workout_id' => 73, 'workout_context_id' => 1],
      ['id' => 87, 'workout_id' => 74, 'workout_context_id' => 1],
      ['id' => 88, 'workout_id' => 75, 'workout_context_id' => 1],
      ['id' => 89, 'workout_id' => 76, 'workout_context_id' => 1],
      ['id' => 90, 'workout_id' => 77, 'workout_context_id' => 1],
      ['id' => 91, 'workout_id' => 78, 'workout_context_id' => 1],
      ['id' => 92, 'workout_id' => 79, 'workout_context_id' => 1],
      ['id' => 93, 'workout_id' => 80, 'workout_context_id' => 1],
      ['id' => 94, 'workout_id' => 81, 'workout_context_id' => 1],
      ['id' => 95, 'workout_id' => 82, 'workout_context_id' => 1],
      ['id' => 96, 'workout_id' => 83, 'workout_context_id' => 1],
      ['id' => 97, 'workout_id' => 84, 'workout_context_id' => 1],
      ['id' => 98, 'workout_id' => 85, 'workout_context_id' => 1],
      ['id' => 99, 'workout_id' => 86, 'workout_context_id' => 1],
      ['id' => 100, 'workout_id' => 87, 'workout_context_id' => 1],
      ['id' => 101, 'workout_id' => 88, 'workout_context_id' => 1],
      ['id' => 102, 'workout_id' => 89, 'workout_context_id' => 1],
      ['id' => 103, 'workout_id' => 90, 'workout_context_id' => 1],
      ['id' => 104, 'workout_id' => 91, 'workout_context_id' => 1],
      ['id' => 105, 'workout_id' => 92, 'workout_context_id' => 1],
      ['id' => 106, 'workout_id' => 92, 'workout_context_id' => 2],
      ['id' => 107, 'workout_id' => 92, 'workout_context_id' => 3],
      ['id' => 108, 'workout_id' => 93, 'workout_context_id' => 1],
      ['id' => 109, 'workout_id' => 94, 'workout_context_id' => 1],
      ['id' => 110, 'workout_id' => 95, 'workout_context_id' => 1],
      ['id' => 111, 'workout_id' => 96, 'workout_context_id' => 1],
      ['id' => 112, 'workout_id' => 97, 'workout_context_id' => 1],
      ['id' => 113, 'workout_id' => 97, 'workout_context_id' => 2],
      ['id' => 114, 'workout_id' => 97, 'workout_context_id' => 3],
      ['id' => 115, 'workout_id' => 97, 'workout_context_id' => 4],
      ['id' => 116, 'workout_id' => 98, 'workout_context_id' => 1],
      ['id' => 117, 'workout_id' => 99, 'workout_context_id' => 1],
      ['id' => 118, 'workout_id' => 100, 'workout_context_id' => 1],
      ['id' => 119, 'workout_id' => 101, 'workout_context_id' => 1],
      ['id' => 120, 'workout_id' => 102, 'workout_context_id' => 1],
      ['id' => 121, 'workout_id' => 103, 'workout_context_id' => 1],
      ['id' => 122, 'workout_id' => 104, 'workout_context_id' => 1],
    ]);
  }
}
