import './bootstrap';
import './admin/workouts/muscle-workout';
import './admin/workouts/workout-calculate';
import './admin/workouts/WorkoutSearch';
import './admin/utils/searchSuggestions';
import './utils/sweetAlert';
import './components/header';
import './components/admin-header';
import './components/admin-sidebar';
import './components/instructions'
import './components/anchor-menu'
import './admin/utils/pagination' 
import './admin/workouts/workout-list'
import './components/user-sidebar'
import './programs/workout-counter';
import './public/workouts/workout-calculate'
import './public/utils/searchSuggestions'
import './admin/blog/blogCategoryModal'
import './admin/blog/blogCategoryStore'
import './admin/blog/blogCategoryEdit'
import './admin/blog/blogCategoryDelete'
import './admin/blog/blogTemaModal'
import './admin/blog/blogTemaStore'
import './admin/blog/blogTemaEdit'
import './admin/blog/blogTemaDelete'
import './admin/blog/calisthenicsProgession'
import './admin/blog/blogLoader'
import './admin/blog/blogSearch'
import './admin/foods/foodView'
import './admin/foods/foodLoader'
import './admin/foods/foodSearch'
import './utils/foodServingCalculator'
import './public/utils/foodSearch'
import './admin/articles/articleModal'
import './admin/articles/articleView'
import './admin/articles/articleLoader'
import './admin/articles/articleSearch'
import './admin/meals/mealCategoryModal'
import './admin/meals/mealCategoryStore'
import './admin/meals/mealCategoryEdit'
import './admin/meals/mealCategoryDelete'
import './admin/meals/mealGoalModal'
import './admin/meals/mealGoalStore'
import './admin/meals/mealGoalEdit'
import './admin/meals/mealGoalDelete'
import './admin/meals/mealItemModal'
import './admin/meals/mealItemIngredients'
import './admin/meals/mealItemSteps'
import './admin/meals/mealItemStore'
import './admin/meals/mealItemView'
import './admin/meals/mealItemEdit'